apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dq-ingress-keycloak
  labels:
    app.kubernetes.io/name: dq-ingress-keycloak
    app.kubernetes.io/part-of: dq-made-easy
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keycloak-placeholder.local
      secretName: dq-keycloak-tls-cert
  rules:
    - host: keycloak-placeholder.local
      http:
        paths:
          - path: /iam
            pathType: Prefix
            backend:
              service:
                name: dq-kong
                port:
                  number: 8443
