variables:
  cloudProvider: eks
  region: eu-west-1
  aksClusterName: dq-made-easy-prod-eks
  aksNamespace: dq-made-easy-prod
  kubeContext: arn:aws:eks:eu-west-1:123456789012:cluster/dq-made-easy-prod-eks
  azureServiceConnection: ''
  ingressDomain: dq-made-easy.jaccloud.nl
