export const APP_PRIMITIVE_COMPONENT_EXPORTS = [
  'AppBadge',
  'AppBanner',
  'AppButton',
  'AppCard',
  'AppCardContent',
  'AppField',
  'AppIcon',
  'AppInput',
  'AppEmptyState',
  'AppListRow',
  'AppPageHeader',
  'AppPageShell',
  'AppModal',
  'AppPanel',
  'AppSelect',
  'AppTagPicker',
  'AppStack',
  'AppTable',
  'AppTabs',
  'AppToolbar',
  'AppTextarea',
] as const

export const APP_PRIMITIVE_SUPPORT_EXPORTS = [
  'APP_ICON_NAMES',
  'APP_ICON_PROVIDER_ICON_NAMES',
  'APP_ICON_PROVIDER_LABELS',
  'APP_ICON_USAGE',
  'APP_ICON_USAGE_BY_SURFACE',
  'APP_PRIMITIVE_COMPONENT_EXPORTS',
  'APP_PRIMITIVE_SUPPORT_EXPORTS',
  'APP_PRIMITIVE_TYPE_EXPORTS',
  'getAppIconNamesForProvider',
] as const

export const APP_PRIMITIVE_TYPE_EXPORTS = [
  'AppBadgeProps',
  'AppBadgeTone',
  'AppBannerProps',
  'AppBannerVariant',
  'AppButtonProps',
  'AppButtonVariant',
  'AppCardContentProps',
  'AppCardProps',
  'AppEmptyStateProps',
  'AppFieldProps',
  'AppIconName',
  'AppIconProps',
  'AppInputProps',
  'AppListRowProps',
  'AppListRowTag',
  'AppPageHeaderProps',
  'AppPageHeaderTitleTag',
  'AppPageShellProps',
  'AppModalProps',
  'AppPanelProps',
  'AppPanelTag',
  'AppPanelTone',
  'AppSelectOption',
  'AppSelectProps',
  'AppTagPickerProps',
  'AppStackGap',
  'AppStackProps',
  'AppTabItem',
  'AppTableProps',
  'AppTabsProps',
  'AppToolbarAlignment',
  'AppToolbarProps',
  'AppTextareaProps',
] as const
