from pydantic import ConfigDict
from app.schemas.pydantic_base import SnakeModel, to_snake_alias


class AppConfigView(SnakeModel):
    model_config = ConfigDict(from_attributes=True, alias_generator=to_snake_alias, populate_by_name=True)

    debounceMs: int = 300
    ssoProvider: str = "none"
    iconProvider: str = "tabler"
    stylePackage: str = "data-web-css"
    ssoIssuer: str | None = None
    ssoClientId: str | None = None
    ssoEnabled: bool = False
    allowLocalAuth: bool = True
    apiVersion: str = "v1"
    apiRetryAttempts: int = 3
    apiRetryDelay: int = 1000
    maxUsersPerWorkspace: int = 100
    maxWorkspaces: int = 50
    maxRulesPerWorkspace: int = 1000
    maxTemplatesPerWorkspace: int = 100
    maxConcurrentTests: int = 5
    allowedWorkspaceDataSourceTypes: list[str] = ["adls", "s3", "oracle", "sql_server"]
    defaultRuleThresholdPct: float = 0.0
    defaultCatalogTermMatchThresholdPct: float = 70.0
    openMetadataContractCacheTtlSeconds: int = 300
    defaultPageSize: int = 20
    maintenanceMode: bool = False
    maintenanceMessage: str = ""
    allowSignup: bool = True
    requireEmailVerification: bool = False
    defaultUserRole: str = "viewer"
    assistanceRequestMode: str = "email"
    assistanceRequestDestinations: list[str] = ["email"]
    assistanceRequestEmailAddress: str = "dq-made-easy-support@jaccloud.nl"
    assistanceRequestItsmSystem: str = "Zammad"
    assistanceRequestItsmEndpointUrl: str = "http://zammad-nginx:8080/api/v1/tickets"
    assistanceRequestItsmAuthToken: str = ""
    assistanceRequestTeamsWebhookUrl: str = "https://example.com/teams/workflow-webhook"
    alertingSlackWebhookUrl: str = ""
    alertingPagerDutyRoutingKey: str = ""
    alertRoutingPolicy: dict[str, object] | None = None
    supportEmailSmtpHost: str = "smtp.strato.com"
    supportEmailSmtpPort: int = 465
    supportEmailSmtpUsername: str = "dq-made-easy-support@jaccloud.nl"
    supportEmailSmtpPassword: str = ""
    supportEmailSmtpUseStartTls: bool = True
    supportEmailFromAddress: str = "dq-made-easy-support@jaccloud.nl"
    dataProtectionMaskingMethods: list[str] = ["none", "redact", "partial", "tokenize"]
    dataProtectionEncryptionMethods: list[str] = ["fernet"]
    logLevel: str = "info"
    enableAnalytics: bool = True
    enableCrashReporting: bool = True
    enableBulkOperations: bool = True
    enableVersioning: bool = True
    enableExport: bool = True
    auditLogRetentionDays: int = 90
    testResultsRetentionDays: int = 30
    deletedItemsRetentionDays: int = 30
    exceptionFactRetentionDays: int = 30
    exceptionFactArchiveRetentionDays: int = 180
    exceptionAnalyticsProjectionRetentionDays: int = 365
    exceptionFactPurgeBatchSize: int = 5000
    exceptionFactJitRoleMaxDurationMinutes: int = 240
    exceptionFactJitRequestTimeoutMinutes: int = 30
    metricsForwardingEnabled: bool = False
    metricsForwardUrl: str | None = None
    featureRuleValidation: bool = True
    featureRuleLifecycleManagement: bool = True
    featureRuleResultAggregation: bool = True
    featureRuleSuggestions: bool = True
    featureExceptionRecordHandling: bool = True
    featureRuleExecutionMonitoring: bool = True
    featureRuleDslV2: bool = False
    featureRuleValidationStage: str = "preview"
    featureRuleLifecycleManagementStage: str = "preview"
    featureRuleResultAggregationStage: str = "preview"
    featureRuleSuggestionsStage: str = "live"
    featureExceptionRecordHandlingStage: str = "preview"
    featureRuleExecutionMonitoringStage: str = "preview"
    featureGovernanceDrift: bool = True
    featureGovernanceDriftStage: str = "live"
    playgroundSourceBundlePolicy: dict[str, object] | None = None
    agentPlatformAllowlist: list[str] = ["mistral_ai", "microsoft_copilot"]
    deploymentVerificationDate: str | None = None
    deploymentVerifiedBy: str | None = None
    agentAccessPolicy: dict[str, object] | None = None
    versionCatalogApi: str = "unknown"
    versionCatalogUi: str = "unknown"
    versionCatalogComponents: dict[str, str] | None = None
    statusGovernance: dict[str, object] | None = None
    incidentGovernance: dict[str, object] | None = None
    sessionTimeoutMinutes: int | None = 60
    sessionTimeoutWarningMinutes: int | None = 10
    agentSessionTimeoutMinutes: int | None = 60
    maxToolCallsPerSession: int | None = 100
