apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-env-dev
  labels:
    app.kubernetes.io/part-of: dq-made-easy
data:
  .env.dev.local: |
    KONG_PUBLIC_URL=https://kong.dev.jac.dot:10443
    SSO_PUBLIC_ISSUER_URL=https://keycloak.dev.jac.dot:10443/auth/realms/dq-made-easy
    UI_NGINX_LOCAL_URL=https://dq-made-easy.dev.jac.dot:10443
    VITE_KEYCLOAK_CLIENT_ID=dq-rules-ui
