from typing import Any, Protocol

from app.domain.entities.data_asset import DataAssetEntity
from app.domain.entities.data_asset import DataAssetContractVersionEntity
from app.domain.entities.data_asset import DataAssetLineageSnapshotEntity
from app.domain.entities.data_asset import DataAssetVersionEntity


class DataAssetRepository(Protocol):
    def list_data_assets(self, workspace_id: str | None = None) -> list[DataAssetEntity]: ...

    def get_data_asset(self, asset_id: str) -> DataAssetEntity | None: ...

    def list_data_asset_versions(self, asset_id: str) -> list[DataAssetVersionEntity]: ...

    def get_data_asset_version(self, asset_id: str, version_id: str) -> DataAssetVersionEntity | None: ...

    def create_data_asset(self, payload: dict[str, Any]) -> DataAssetEntity: ...

    def update_data_asset(self, asset_id: str, payload: dict[str, Any]) -> DataAssetEntity: ...

    def delete_data_asset(self, asset_id: str) -> bool: ...

    def create_data_asset_version(self, asset_id: str, payload: dict[str, Any]) -> DataAssetVersionEntity: ...

    def get_latest_data_asset_contract_version(self, asset_id: str) -> DataAssetContractVersionEntity | None: ...

    def list_data_asset_contract_versions(self, asset_id: str) -> list[DataAssetContractVersionEntity]: ...

    def update_data_asset_contract_version_review(self, asset_id: str, version_id: str, payload: dict[str, Any]) -> DataAssetContractVersionEntity: ...

    def save_data_asset_contract_version(self, asset_id: str, payload: dict[str, Any]) -> DataAssetContractVersionEntity: ...

    def record_data_asset_lineage_snapshot(self, asset_id: str, payload: dict[str, Any]) -> DataAssetLineageSnapshotEntity: ...

    def list_data_asset_lineage_snapshots(self, asset_id: str, limit: int = 20) -> list[DataAssetLineageSnapshotEntity]: ...
