#!/usr/bin/env python3
"""Generate random passwords for mock seed users.

Reads the mock-data users CSV (password column not required), generates
random passwords for every user with an email, and writes out a users CSV
(with password column), a credentials CSV, and a credentials env file.

Designed to replace the inline heredoc in
dq-keycloak/scripts/generate_seed_artifacts.sh.
"""

import csv
import os
import secrets
import shlex
import string
import sys
from pathlib import Path


ALLOWED_PASSWORD_CHARS = string.ascii_letters + string.digits + "-_"
PASSWORD_LENGTH = 32


def generate_password() -> str:
    """Return a cryptographically random password."""
    return "".join(secrets.choice(ALLOWED_PASSWORD_CHARS) for _ in range(PASSWORD_LENGTH))


def _shell_quote(value: str) -> str:
    """Shell-quote a value for safe embedding in env files."""
    return shlex.quote(value)


def generate_user_passwords(source_csv: Path) -> tuple[list[str], list[dict[str, str]]]:
    """Read *source_csv* and generate a random password for every user with an email.

    The source CSV may or may not have a ``password`` column — if it does, values
    are replaced; if it doesn't, the column is appended.

    Returns ``(fieldnames, rows)`` where *fieldnames* always includes ``password``
    and *rows* contain freshly generated passwords.
    Raises SystemExit if the source is missing.
    """
    if not source_csv.exists():
        raise SystemExit(f"Source users CSV not found: {source_csv}")

    with source_csv.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        fieldnames = list(reader.fieldnames or [])
        if "first_name" not in fieldnames or "last_name" not in fieldnames:
            raise SystemExit(f"{source_csv} is missing required columns: first_name, last_name")
        rows = list(reader)

    # Ensure password column exists in fieldnames
    if "password" not in fieldnames:
        fieldnames.append("password")

    seen_passwords: set[str] = set()
    for row in rows:
        email = (row.get("email") or "").strip()
        if not email:
            continue
        new_password = generate_password()
        while new_password in seen_passwords:
            new_password = generate_password()
        seen_passwords.add(new_password)
        row["password"] = new_password

    return fieldnames, rows


def write_rotated_users_csv(fieldnames: list[str], rows: list[dict[str, str]], output: Path) -> None:
    """Write the rotated user rows to a new CSV using the given *fieldnames*."""
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, quoting=csv.QUOTE_ALL, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def write_credentials_csv(rows: list[dict[str, str]], output: Path) -> None:
    """Write an ``email,password`` CSV for seed-credential tracking."""
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=["email", "password"], quoting=csv.QUOTE_ALL, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            email = (row.get("email") or "").strip()
            if email:
                writer.writerow({"email": email, "password": row.get("password", "")})


def _password_by_email(rows: list[dict[str, str]]) -> dict[str, str]:
    return {(row.get("email") or "").strip(): row.get("password", "") for row in rows}


# Default credential aliases sourced from environment variables.
# Each triple: (username_key, password_key, env_var_for_email)
DEFAULT_CREDENTIAL_ALIASES = [
    ("KEYCLOAK_JACCLOUD_USERNAME", "KEYCLOAK_JACCLOUD_PASSWORD", "KEYCLOAK_JACCLOUD_USERNAME"),
    ("SMOKE_LOGIN_EMAIL", "SMOKE_LOGIN_PASSWORD", "SMOKE_LOGIN_EMAIL"),
    ("OPERATOR_LOGIN_EMAIL", "OPERATOR_LOGIN_PASSWORD", "OPERATOR_LOGIN_EMAIL"),
    ("AUDITOR_LOGIN_EMAIL", "AUDITOR_LOGIN_PASSWORD", "AUDITOR_LOGIN_EMAIL"),
    ("REGULATOR_LOGIN_EMAIL", "REGULATOR_LOGIN_PASSWORD", "REGULATOR_LOGIN_EMAIL"),
]


def write_credentials_env(
    rows: list[dict[str, str]],
    output: Path,
    credential_aliases: list[tuple[str, str, str]] | None = None,
) -> None:
    """Write a shell-sourceable env file with username/password pairs.

    *credential_aliases* is a list of ``(username_key, password_key,
    email_env_var)`` triples.  The email is read from ``os.environ`` using
    ``email_env_var``, then looked up in the rows.
    """
    credential_aliases = credential_aliases or DEFAULT_CREDENTIAL_ALIASES
    password_map = _password_by_email(rows)

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as fh:
        fh.write("# Generated by scripts/supporting/seed_password_rotation.py\n")
        fh.write("# Do not commit. Credentials rotate on each seed-artifacts run.\n")

        for username_key, password_key, email_env_var in credential_aliases:
            selected_email = (os.environ.get(email_env_var) or "").strip()
            if not selected_email:
                continue
            if selected_email not in password_map:
                raise SystemExit(f"{username_key} not found in users.csv: {selected_email}")
            fh.write(f"{username_key}={_shell_quote(selected_email)}\n")
            fh.write(f"{password_key}={_shell_quote(password_map[selected_email])}\n")


def _restrict_permissions(path: Path) -> None:
    """Best-effort permission tightening on sensitive output files."""
    try:
        os.chmod(path, 0o640)
    except OSError:
        pass


def generate_and_write(
    source_csv: str | Path,
    rotated_users_csv: str | Path,
    credentials_csv: str | Path,
    credentials_env: str | Path,
    credential_aliases: list[tuple[str, str, str]] | None = None,
) -> None:
    """Full pipeline: generate passwords, write all output artifacts.

    This is the main convenience entry point used by the seed-artifacts script.
    """
    fieldnames, rows = generate_user_passwords(Path(source_csv))

    rotated_users_csv_path = Path(rotated_users_csv)
    credentials_csv_path = Path(credentials_csv)
    credentials_env_path = Path(credentials_env)

    write_rotated_users_csv(fieldnames, rows, rotated_users_csv_path)
    write_credentials_csv(rows, credentials_csv_path)
    write_credentials_env(rows, credentials_env_path, credential_aliases)

    _restrict_permissions(credentials_csv_path)
    _restrict_permissions(credentials_env_path)


def main() -> None:
    """CLI entry point for use from shell scripts.

    Usage::

        python -m scripts.supporting.seed_password_rotation \\
            --source mock-data/users.csv \\
            --rotated-users /seed-data/users.csv \\
            --credentials-csv /seed-data/keycloak_seed_user_credentials.csv \\
            --credentials-env /seed-data/keycloak_seed_user_credentials.env
    """
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate random passwords for mock seed users"
    )
    parser.add_argument("--source", required=True, help="Path to the source users CSV")
    parser.add_argument("--rotated-users", required=True, help="Output path for users CSV with generated passwords")
    parser.add_argument("--credentials-csv", required=True, help="Output path for email,password CSV")
    parser.add_argument("--credentials-env", required=True, help="Output path for shell-sourceable env file")
    args = parser.parse_args()

    generate_and_write(
        source_csv=args.source,
        rotated_users_csv=args.rotated_users,
        credentials_csv=args.credentials_csv,
        credentials_env=args.credentials_env,
    )


if __name__ == "__main__":
    main()
