"""SQLAlchemy ORM layer for the FastAPI application.

Import ``Base`` to access the shared metadata (e.g. for ``create_all``).
Import individual ``*Row`` classes to build queries and sessions.
"""

from app.infrastructure.orm.base import Base
from app.infrastructure.orm.models import (
    AppConfigRow,
    ApprovalRow,
    AttributeCatalogRow,
    AuditRow,
    BatchTestRequestRow,
    DataDeliveryRow,
    DataAssetRow,
    DataAssetContractVersionRow,
    DataAssetVersionRow,
    MasterRecordRow,
    DataObjectCatalogRow,
    DataObjectRow,
    DataObjectVersionRow,
    DataProductRow,
    DataSetRow,
    DataSourceMetadataRow,
    DataSourceProfilingRequestRow,
    ExceptionReasonAnalyticsProjectionRow,
    DqResultEventRow,
    GxExecutionRunRow,
    GxExecutionRunStatusHistoryRow,
    GxExecutionViolationRow,
    GxRunPlanTransitionRow,
    ReusableFilterRow,
    ReusableJoinRow,
    RoleRow,
    RuleAttributeRow,
    RuleReusableFilterRow,
    RuleRollbackRow,
    RuleRow,
    RuleVersionDiffRow,
    RuleVersionCompilerArtifactRow,
    RuleVersionRelationshipRow,
    RuleVersionRow,
    SuggestionInteractionRow,
    SuggestionPreviewInteractionRow,
    SuggestionRow,
    SystemInfoRow,
    TestProofRow,
    UserRoleRow,
    UserRow,
    WorkspaceRow,
)

__all__ = [
    "Base",
    "AppConfigRow",
    "ApprovalRow",
    "AttributeCatalogRow",
    "AuditRow",
    "BatchTestRequestRow",
    "DataDeliveryRow",
    "DataAssetRow",
    "DataAssetContractVersionRow",
    "DataAssetVersionRow",
    "MasterRecordRow",
    "DataObjectCatalogRow",
    "DataObjectRow",
    "DataObjectVersionRow",
    "DataProductRow",
    "DataSetRow",
    "DataSourceMetadataRow",
    "DataSourceProfilingRequestRow",
    "ExceptionReasonAnalyticsProjectionRow",
    "DqResultEventRow",
    "GxExecutionRunRow",
    "GxExecutionRunStatusHistoryRow",
    "GxExecutionViolationRow",
    "GxRunPlanTransitionRow",
    "ReusableFilterRow",
    "ReusableJoinRow",
    "RoleRow",
    "RuleAttributeRow",
    "RuleReusableFilterRow",
    "RuleRollbackRow",
    "RuleRow",
    "RuleVersionDiffRow",
    "RuleVersionCompilerArtifactRow",
    "RuleVersionRelationshipRow",
    "RuleVersionRow",
    "SuggestionInteractionRow",
    "SuggestionPreviewInteractionRow",
    "SuggestionRow",
    "SystemInfoRow",
    "TestProofRow",
    "UserRoleRow",
    "UserRow",
    "WorkspaceRow",
]
