apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credential-api
  labels:
    platform.jaccloud.nl/managed-by: argocd
    platform.jaccloud.nl/tenant: dq
    platform.jaccloud.nl/service: dq-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets-store
    kind: ClusterSecretStore
  target:
    name: redis-credential-api
    creationPolicy: Owner
  data:
    - secretKey: REDIS_HOST
      remoteKey: redis-credentials-dq-api
      property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteKey: redis-credentials-dq-api
      property: REDIS_PORT
    - secretKey: REDIS_TLS_ENABLED
      remoteKey: redis-credentials-dq-api
      property: REDIS_TLS_ENABLED
    - secretKey: REDIS_USERNAME
      remoteKey: redis-credentials-dq-api
      property: REDIS_USERNAME
    - secretKey: REDIS_PASSWORD
      remoteKey: redis-credentials-dq-api
      property: REDIS_PASSWORD
    - secretKey: REDIS_KEY_PREFIX
      remoteKey: redis-credentials-dq-api
      property: REDIS_KEY_PREFIX
