apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-credential-engine
  labels:
    platform.jaccloud.nl/managed-by: argocd
    platform.jaccloud.nl/tenant: dq
    platform.jaccloud.nl/service: dq-engine
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: platform-secrets-store
    kind: ClusterSecretStore
  target:
    name: redis-credential-engine
    creationPolicy: Owner
  data:
    - secretKey: REDIS_HOST
      remoteRef:
        key: redis-credentials-dq-engine
        property: REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: redis-credentials-dq-engine
        property: REDIS_PORT
    - secretKey: REDIS_TLS_ENABLED
      remoteRef:
        key: redis-credentials-dq-engine
        property: REDIS_TLS_ENABLED
    - secretKey: REDIS_USERNAME
      remoteRef:
        key: redis-credentials-dq-engine
        property: REDIS_USERNAME
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: redis-credentials-dq-engine
        property: REDIS_PASSWORD
    - secretKey: REDIS_KEY_PREFIX
      remoteRef:
        key: redis-credentials-dq-engine
        property: REDIS_KEY_PREFIX
