apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dq-ui
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dq-ui.example.invalid
      secretName: dq-ui-tls
  rules:
    - host: dq-ui.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dq-frontend
                port:
                  number: 443