apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-api-config
data:
  DQ_API_PORT: "8000"
  SSO_INTERNAL_ISSUER_URL: https://keycloak.platform-keycloak.svc.cluster.local:8443/auth/realms/jaccloud
  KONG_PUBLIC_URL: https://kong.dev.jac.dot:10443
  REDIS_CA_BUNDLE: /etc/ssl/certs/platform-root-ca.pem
  REDIS_DB: "0"
  GX_EXECUTION_QUEUE_KEY: dq-made-easy:gx-execution
  GX_JOIN_PAIR_MATERIALIZATION_QUEUE_KEY: dq-made-easy:gx-join-pair-materialization
  PROFILING_QUEUE_KEY: dq-made-easy:profiling
  NATURAL_LANGUAGE_DRAFT_QUEUE_KEY: dq-made-easy:natural-language-draft
  TEST_DATA_MATERIALIZATION_QUEUE_KEY: dq-made-easy:test-data-materialization