apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-engine-config
data:
  DQ_ENGINE_PORT: "8000"
  REDIS_CA_BUNDLE: /etc/ssl/certs/platform-root-ca.pem
  REDIS_DB: "0"
  GX_EXECUTION_QUEUE_KEY: dq-made-easy:gx-execution
  GX_JOIN_PAIR_MATERIALIZATION_QUEUE_KEY: dq-made-easy:gx-join-pair-materialization
  TEST_DATA_MATERIALIZATION_QUEUE_KEY: dq-made-easy:test-data-materialization