ARG PYTHON_DOCKER_REGISTRY
ARG PYTHON_DOCKER_NAMESPACE
ARG PYTHON_DOCKER_IMAGE
ARG PYTHON_DOCKER_TAG

FROM ${PYTHON_DOCKER_REGISTRY}${PYTHON_DOCKER_NAMESPACE}${PYTHON_DOCKER_IMAGE}:${PYTHON_DOCKER_TAG}

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY dq-api/scripts/generate_keycloak_realm.py /app/generate_keycloak_realm.py
COPY dq-db/mock-data /app/mock-data
COPY dq-keycloak/scripts/generate_seed_artifacts.sh /app/generate_seed_artifacts.sh
COPY scripts/supporting/seed_password_rotation.py /app/seed_password_rotation.py

RUN chmod +x /app/generate_seed_artifacts.sh

ENTRYPOINT ["/app/generate_seed_artifacts.sh"]