apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-kafka-consumer-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  KAFKA_CONSUMER_METRICS_PORT: '9100'
