apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-profiling-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  DQ_PROFILING_METRICS_PORT: '8001'
  REDIS_HOST: redis.platform-redis.svc.cluster.local
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_USERNAME: dq-profiling
  REDIS_TLS_ENABLED: 'true'
  REDIS_CA_BUNDLE: /etc/ssl/certs/platform-root-ca.pem
  PROFILING_QUEUE_KEY: dq-made-easy:profiling
  TEST_DATA_MATERIALIZATION_QUEUE_KEY: dq-made-easy:test-data-materialization
