apiVersion: v1
kind: Secret
metadata:
  name: dq-api-tls
  namespace: dq-dev
type: kubernetes.io/tls
data:
  tls.crt: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
D
R
V
J
U
S
U
Z
J
Q
0
F
U
R
S
0
t
L
S
0
t
C
k
1
J
S
U
R
a
V
E
N
D
Q
W
s
y
Z
0
F
3
S
U
J
B
Z
0
l
V
U
V
V
j
N
2
g
4
R
F
R
4
N
3
U
3
Q
m
x
w
O
E
p
K
M
2
V
h
Z
k
d
q
N
n
d
z
d
0
R
R
W
U
p
L
b
1
p
J
a
H
Z
j
T
k
F
R
R
U
w
K
Q
l
F
B
d
0
h
U
R
W
J
N
Q
m
t
H
Q
T
F
V
R
U
F
3
d
1
N
a
S
E
V
0
W
V
h
C
c
E
x
t
U
m
x
k
a
T
V
x
W
V
d
N
d
V
p
H
O
T
B
N
Q
j
R
Y
R
F
R
J
M
k
1
E
Z
3
h
O
R
E
l
6
T
X
p
N
e
g
p
N
V
m
9
Y
R
F
R
J
M
0
1
E
Z
3
h
O
R
E
l
6
T
X
p
N
e
k
1
W
b
3
d
I
V
E
V
i
T
U
J
r
R
0
E
x
V
U
V
B
d
3
d
T
W
k
h
F
d
F
l
Y
Q
n
B
M
b
V
J
s
Z
G
k
1
c
V
l
X
T
X
V
a
R
z
k
w
C
k
1
J
S
U
J
J
a
k
F
O
Q
m
d
r
c
W
h
r
a
U
c
5
d
z
B
C
Q
V
F
F
R
k
F
B
T
0
N
B
U
T
h
B
T
U
l
J
Q
k
N
n
S
0
N
B
U
U
V
B
M
l
M
4
e
k
Z
6
a
3
l
Y
M
n
B
Y
Y
W
s
z
a
X
d
0
a
y
s
K
V
D
F
n
R
G
p
z
M
V
l
y
c
W
x
M
e
W
1
w
b
j
I
y
c
m
5
i
d
k
V
i
V
l
R
m
U
n
h
1
N
1
l
H
V
1
B
O
N
m
N
z
R
E
Z
s
c
D
B
o
W
X
d
w
a
3
Z
a
V
k
1
R
Y
k
Y
1
U
k
R
v
Z
n
k
0
V
A
p
n
S
k
s
0
R
m
p
S
R
1
o
1
Q
W
t
M
c
2
Z
4
e
E
l
R
M
k
5
a
Z
F
d
s
R
n
B
V
V
W
l
m
U
2
l
5
V
0
J
I
M
V
o
2
Z
W
t
V
S
j
J
4
W
W
l
3
Z
U
l
q
b
2
p
S
N
E
R
1
b
m
d
Z
c
1
R
Y
C
j
B
q
Q
2
8
x
W
D
l
F
c
k
5
K
c
j
l
0
M
T
R
I
d
0
J
O
U
E
N
M
W
H
l
F
Z
3
R
B
d
W
9
D
V
2
5
X
V
H
h
J
N
S
9
V
a
E
J
L
a
z
Z
X
e
G
1
X
M
U
p
w
R
T
B
S
d
V
F
z
T
W
x
l
U
W
4
K
V
z
h
r
U
W
F
v
b
1
J
B
M
n
l
F
Q
i
9
6
Q
T
h
w
b
0
V
q
W
W
x
t
O
G
5
O
U
X
g
3
T
0
9
W
a
F
d
X
d
z
J
z
c
z
d
G
d
k
V
I
N
j
B
5
b
3
h
q
V
E
k
r
c
1
N
G
Y
T
N
3
N
m
w
4
Y
Q
p
x
W
E
x
u
c
W
9
C
W
X
V
3
V
W
N
B
d
3
l
P
L
0
9
B
Z
S
9
v
c
E
Z
a
L
0
s
3
W
C
t
s
M
U
F
J
S
n
c
z
R
j
B
p
L
0
p
h
Q
2
Z
O
b
3
J
3
Q
0
F
H
V
j
J
5
Y
z
V
C
V
y
t
P
U
S
t
r
C
m
t
R
S
U
R
B
U
U
F
C
b
z
R
H
Y
0
1
J
R
1
p
N
Q
j
B
H
Q
T
F
V
Z
E
R
n
U
V
d
C
Q
l
F
O
M
k
x
Z
M
2
N
u
b
W
5
C
Z
W
g
0
b
2
F
G
W
G
9
x
Y
m
F
m
S
3
A
x
U
V
R
B
Z
k
J
n
T
l
Y
K
S
F
N
N
R
U
d
E
Q
V
d
n
Q
l
F
O
M
k
x
Z
M
2
N
u
b
W
5
C
Z
W
g
0
b
2
F
G
W
G
9
x
Y
m
F
m
S
3
A
x
U
V
R
B
U
E
J
n
T
l
Z
I
U
k
1
C
Q
W
Y
4
R
U
J
U
Q
U
R
B
U
U
g
v
T
U
V
Z
R
w
p
B
M
V
V
k
R
V
F
R
L
0
1
E
M
k
N
F
b
V
J
4
T
F
d
G
d
2
F
T
N
W
t
a
W
F
l
1
Y
W
1
G
a
k
x
t
U
n
Z
k
S
U
l
H
W
k
h
F
d
F
l
Y
Q
n
B
n
a
D
l
r
Y
1
M
x
a
G
N
H
a
3
V
a
S
E
V
0
C
l
p
H
V
j
J
M
b
k
4
y
W
X
k
1
a
m
J
I
V
n
p
k
R
1
Z
5
T
G
1
4
d
l
k
y
R
n
N
N
Q
T
B
H
Q
1
N
x
R
1
N
J
Y
j
N
E
U
U
V
C
Q
3
d
V
Q
U
E
0
S
U
J
B
U
U
J
z
b
U
J
J
c
j
V
5
R
W
M
K
S
W
4
y
V
1
N
k
S
z
l
p
d
S
9
F
a
l
k
y
N
X
V
W
T
0
0
2
d
l
R
V
R
l
k
w
M
y
8
r
Z
z
Z
Y
U
2
l
F
M
0
p
U
N
m
R
t
d
i
9
3
Q
m
N
H
S
2
V
T
Z
U
1
J
c
T
N
Z
R
U
h
l
O
U
t
I
M
A
o
w
M
k
Z
j
T
2
l
R
W
H
Z
4
Z
1
d
h
Z
2
F
2
S
2
R
t
b
0
w
1
Q
W
p
m
c
z
J
k
d
D
M
0
N
0
d
j
a
0
s
v
S
n
l
3
a
F
B
u
d
2
N
q
N
V
A
v
e
E
U
v
S
m
x
U
L
3
d
K
T
n
B
W
U
m
1
C
C
k
U
4
e
i
t
5
S
H
o
r
S
G
Z
p
a
l
d
G
S
E
V
S
M
V
J
n
S
V
h
X
c
k
1
W
e
U
9
4
W
H
p
w
b
2
9
q
R
m
Z
M
M
X
J
3
N
G
4
0
O
U
g
v
T
H
U
3
M
k
9
0
d
F
h
q
R
3
F
l
V
W
p
3
U
z
U
K
W
j
d
S
b
H
p
C
Z
1
p
N
R
l
d
0
V
D
d
o
R
k
Z
E
b
S
t
w
a
H
p
l
V
D
R
y
S
T
R
v
U
k
N
t
c
F
l
3
U
H
J
3
W
C
9
Z
K
1
d
H
O
G
Z
U
a
m
N
U
Z
F
J
U
R
0
1
K
c
V
d
H
U
U
R
5
M
g
p
4
R
1
p
1
O
G
N
D
O
T
R
l
T
3
d
6
d
y
t
E
a
y
9
J
Z
z
d
i
W
C
9
j
b
V
d
m
d
2
x
1
V
D
R
B
R
k
d
Z
M
X
N
m
c
1
B
k
U
l
h
G
V
U
V
G
W
G
N
D
c
n
h
H
T
i
9
t
S
D
Z
Q
T
m
o
2
C
k
V
w
T
0
t
m
V
j
Z
h
R
j
B
z
c
Q
o
t
L
S
0
t
L
U
V
O
R
C
B
D
R
V
J
U
S
U
Z
J
Q
0
F
U
R
S
0
t
L
S
0
t
C
g
=
=
  tls.key: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
Q
U
k
l
W
Q
V
R
F
I
E
t
F
W
S
0
t
L
S
0
t
C
k
1
J
S
U
V
2
U
U
l
C
Q
U
R
B
T
k
J
n
a
3
F
o
a
2
l
H
O
X
c
w
Q
k
F
R
R
U
Z
B
Q
V
N
D
Q
k
t
j
d
2
d
n
U
2
p
B
Z
0
V
B
Q
W
9
J
Q
k
F
R
R
F
p
M
e
k
1
Y
T
1
R
K
Z
m
F
s
Z
H
E
K
V
G
V
M
Q
z
J
U
N
V
B
X
Q
U
9
P
e
l
Z
p
d
X
F
V
d
k
t
h
b
W
Z
i
Y
X
V
k
d
T
h
S
d
F
Z
O
O
U
h
H
N
3
R
n
W
l
k
4
M
3
B
5
d
0
1
X
V
2
5
T
R
m
p
D
b
V
M
5
b
F
V
4
Q
n
N
Y
b
A
p
F
T
2
g
v
T
G
h
P
Q
W
t
y
Z
1
d
O
R
V
p
u
a
0
N
R
d
X
g
v
S
E
V
o
R
F
k
x
b
D
F
h
V
V
d
s
U
l
N
K
O
U
t
M
S
l
l
F
Z
l
Z
u
c
D
Z
S
U
W
5
i
R
m
l
M
Q
j
R
p
T
2
l
O
S
G
d
P
C
j
Z
l
Q
m
l
4
T
m
Z
T
T
U
t
q
V
m
Y
w
U
3
M
w
b
X
Y
y
M
1
h
n
Z
k
F
F
M
D
h
J
d
G
Z
J
U
0
M
w
Q
z
Z
n
S
m
F
k
W
l
B
F
a
m
4
5
U
0
V
F
c
V
R
w
Y
k
d
a
Y
l
V
t
a
1
R
S
R
z
U
K
Q
3
d
5
V
j
V
D
Z
G
J
5
U
k
J
x
a
W
h
F
R
G
J
J
U
U
g
v
T
U
R
5
b
W
d
T
T
m
l
X
Y
n
l
j
M
U
R
I
c
z
Q
1
V
0
Z
a
Y
k
R
h
e
X
p
z
V
z
h
R
Z
n
J
U
S
2
p
H
T
k
1
q
N
n
h
J
V
g
p
y
Z
k
R
x
W
H
h
x
c
G
N
1
Z
X
F
n
R
m
k
3
Q
l
J
3
R
E
R
J
N
z
g
0
Q
j
c
r
a
W
t
W
b
j
h
y
d
G
Y
2
W
F
V
B
Z
2
5
E
Y
1
h
T
T
D
h
s
b
0
o
4
M
m
l
2
Q
U
l
B
W
l
h
i
S
n
p
r
C
k
Z
i
N
D
V
E
N
l
N
S
Q
W
d
N
Q
k
F
B
R
U
N
n
Z
j
l
v
a
j
V
E
S
l
h
Z
Q
W
k
3
O
C
t
t
S
G
x
s
T
j
l
j
b
E
o
2
Z
F
h
N
c
X
B
C
S
G
h
y
b
z
J
l
W
V
F
H
M
3
p
F
T
S
t
J
Z
H
c
K
U
D
Y
5
L
1
Z
2
N
H
p
P
e
G
1
u
d
F
Z
X
S
E
x
Z
V
n
J
4
a
z
g
5
c
2
R
y
U
i
8
3
R
E
c
x
N
T
B
Y
b
m
R
k
R
n
o
x
M
V
J
V
M
W
1
T
Q
X
B
O
b
z
h
s
b
3
p
n
b
k
9
X
M
l
l
X
V
g
p
a
d
W
V
4
c
G
Z
w
M
2
c
x
Y
m
0
v
M
3
Q
z
N
G
t
V
Y
2
R
V
d
k
d
q
R
m
t
i
Z
n
F
k
T
2
h
z
c
k
F
3
b
1
F
s
Y
m
N
m
Y
k
F
h
c
k
9
p
W
C
9
4
R
2
k
3
N
n
Z
l
c
H
h
T
S
E
Z
Q
C
j
F
S
Q
j
J
K
R
1
V
h
e
G
V
6
V
H
R
6
Z
n
N
s
N
3
B
l
Y
n
d
M
c
l
p
5
Z
F
N
X
b
E
c
v
O
V
V
Z
Y
k
F
2
c
j
Z
q
U
X
Z
y
R
y
t
u
N
T
N
P
M
W
Z
u
Y
W
R
5
Y
U
R
h
R
F
A
y
Q
0
E
K
Z
l
l
a
e
E
N
z
M
0
8
w
Q
k
R
p
Y
T
V
k
e
m
5
l
S
G
9
m
S
D
l
t
U
G
Q
4
N
m
Y
x
N
k
J
a
S
V
B
r
Z
0
l
L
b
2
M
2
S
U
h
V
L
3
V
G
L
3
R
0
S
E
t
R
Z
3
d
2
a
k
l
1
N
X
Z
s
N
g
o
z
V
i
t
S
V
2
p
3
V
T
F
S
e
m
J
U
a
D
l
r
O
D
Z
l
U
G
t
I
e
X
F
U
Z
n
F
Q
N
F
F
5
b
2
J
H
S
C
9
E
U
k
V
D
Z
1
l
F
Q
S
8
3
b
1
N
k
R
H
l
G
S
m
Z
V
b
m
9
W
Q
n
h
j
V
0
Y
x
C
j
A
1
Z
n
Z
l
V
D
Z
w
V
D
N
F
U
k
t
3
M
0
E
3
c
1
V
N
d
T
B
n
T
2
Z
V
T
U
h
l
T
2
Z
s
e
j
I
v
T
m
x
y
Q
2
J
G
W
E
1
2
N
l
d
p
R
D
B
X
T
F
E
v
b
D
B
6
S
D
V
J
T
U
l
v
R
T
E
K
b
2
V
B
Y
T
U
1
d
T
d
n
K
0
Q
z
S
T
E
z
c
T
k
w
M
1
B
T
a
n
d
C
c
k
R
L
R
m
l
l
T
m
o
w
d
j
V
T
a
X
R
S
Z
k
R
r
b
G
t
5
Z
1
I
x
e
n
d
t
Z
W
5
E
Z
C
t
w
c
n
A
5
c
1
Q
r
b
w
p
X
Q
0
9
m
W
D
V
n
V
H
B
Y
V
2
g
4
Q
l
p
M
V
m
Z
W
c
l
p
K
a
0
N
n
W
U
V
B
M
l
d
x
V
2
t
D
N
V
d
u
c
H
Y
v
Z
W
N
a
a
W
l
z
c
1
d
4
Z
j
M
0
N
z
N
G
R
n
B
K
T
E
V
M
U
k
9
i
C
k
V
z
Z
H
J
3
V
U
h
n
O
H
N
O
O
H
R
n
e
H
B
U
d
G
g
3
O
W
E
1
b
G
F
0
c
1
V
x
Q
j
Y
0
N
n
d
Z
O
D
d
M
Y
X
g
2
c
F
N
V
a
z
B
D
b
n
h
z
N
G
Z
1
d
W
k
v
N
1
M
1
e
i
9
V
Q
k
8
K
R
0
x
I
U
T
d
L
Z
X
Q
1
d
D
V
i
W
G
5
n
a
F
J
s
K
1
F
X
Y
U
R
z
U
l
U
2
b
G
F
m
c
G
8
r
Z
n
B
1
a
1
V
O
c
1
I
y
Y
2
J
O
Q
X
k
r
U
2
9
S
a
3
d
s
V
W
p
j
a
3
Q
v
c
X
l
0
U
Q
o
w
R
W
o
0
d
3
J
r
Q
2
d
Z
R
U
F
o
O
W
h
T
Z
1
V
p
O
C
t
t
T
D
J
3
R
3
k
1
T
n
A
r
d
E
5
j
L
2
F
P
T
E
F
l
e
E
1
L
d
G
V
n
O
S
t
V
O
W
g
5
W
U
9
k
d
0
9
2
N
W
1
j
O
F
h
N
C
m
d
K
d
E
Z
2
U
3
p
u
M
V
V
j
e
F
J
t
N
X
N
4
O
G
d
V
Z
V
d
z
T
k
E
x
S
l
Q
r
K
2
h
q
a
3
p
B
M
1
d
w
M
l
J
5
U
W
F
5
Z
2
l
r
Y
j
d
t
O
T
V
G
R
m
c
0
R
X
o
5
c
l
R
N
c
H
M
K
Z
H
V
M
K
y
t
o
e
k
N
1
a
F
l
t
N
G
1
I
b
0
t
5
b
F
R
C
b
T
A
4
Y
k
Z
s
W
T
k
5
V
j
N
H
Z
3
N
p
V
0
d
l
e
T
J
B
e
G
J
E
K
3
p
u
N
0
N
2
S
T
l
0
R
U
N
n
W
U
V
B
e
H
N
u
d
w
p
W
S
E
F
w
L
3
V
l
L
2
x
Z
W
l
F
m
M
3
J
s
b
m
E
1
e
n
Q
r
c
W
5
0
S
3
d
F
O
X
Z
v
Z
0
p
m
R
j
B
r
c
1
U
3
Z
W
5
4
S
F
F
P
V
G
t
Q
S
l
V
2
O
G
h
p
O
D
N
o
R
G
1
P
R
G
1
1
C
j
l
p
V
k
Q
r
M
k
9
v
R
l
V
Z
N
C
t
0
S
j
V
G
U
X
R
P
Y
z
h
W
d
0
J
0
c
2
N
i
b
2
d
u
W
C
t
q
b
G
t
C
e
F
l
v
d
W
p
Z
U
G
U
0
M
D
d
u
V
m
V
O
T
F
V
3
a
3
N
Z
d
j
l
G
Q
m
o
K
U
D
M
w
O
U
w
x
Q
2
9
a
a
m
p
k
N
U
o
5
c
U
5
o
U
U
x
W
S
3
d
u
d
H
M
5
V
k
1
o
c
H
V
6
N
k
t
J
N
F
B
F
Q
2
d
Z
R
U
F
n
T
0
Y
r
V
C
9
H
Y
j
Z
X
R
W
g
5
S
T
F
H
N
z
l
x
Q
Q
p
x
T
0
V
W
Y
k
h
l
W
U
E
r
V
E
V
1
L
0
Z
W
M
S
t
r
Z
0
1
W
Z
k
J
I
b
z
R
3
N
m
s
1
M
n
V
t
Z
k
0
y
Q
U
9
3
U
H
h
s
Q
2
1
p
Q
z
d
S
S
z
B
I
c
D
Y
r
Q
X
Z
N
S
D
d
w
R
F
J
m
C
l
l
Y
S
0
k
w
Z
1
R
Y
V
G
U
3
b
X
l
w
W
E
1
Z
e
H
Z
6
Z
n
N
w
S
D
F
S
V
m
5
N
N
E
p
T
M
W
t
s
V
H
N
j
M
n
F
U
O
F
Z
v
S
3
B
5
W
U
9
t
W
l
J
M
d
W
h
a
a
z
l
y
R
E
p
M
a
l
U
K
S
l
R
5
V
2
t
M
V
l
R
P
U
1
B
T
T
D
M
3
S
m
1
H
b
W
E
0
O
D
g
9
C
i
0
t
L
S
0
t
R
U
5
E
I
F
B
S
S
V
Z
B
V
E
U
g
S
0
V
Z
L
S
0
t
L
S
0
K
