apiVersion: v1
kind: Secret
metadata:
  name: dq-dev-tls-cert
  namespace: dq-dev
type: Opaque
data:
  tls.crt: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
D
R
V
J
U
S
U
Z
J
Q
0
F
U
R
S
0
t
L
S
0
t
C
k
1
J
S
U
R
i
R
E
N
D
Q
W
x
T
Z
0
F
3
S
U
J
B
Z
0
l
V
Z
U
l
U
U
H
c
4
Z
k
x
5
a
2
s
y
V
l
o
5
S
n
Z
n
V
G
R
H
Q
X
l
Q
V
z
R
F
d
0
R
R
W
U
p
L
b
1
p
J
a
H
Z
j
T
k
F
R
R
U
w
K
Q
l
F
B
d
0
h
E
R
W
F
N
Q
m
d
H
Q
T
F
V
R
U
F
3
d
1
J
a
S
E
V
0
Z
F
d
r
d
V
p
H
V
j
J
M
b
X
B
o
W
X
k
1
a
2
I
z
U
X
d
I
a
G
N
O
T
W
p
Z
d
0
9
E
R
T
B
N
a
k
1
6
T
X
p
N
e
A
p
X
a
G
N
O
T
W
p
j
d
0
9
E
R
T
B
N
a
k
1
6
T
X
p
N
e
F
d
q
Q
W
N
N
U
m
9
3
R
0
F
Z
R
F
Z
R
U
U
R
E
Q
k
Z
r
Y
1
M
x
M
W
F
T
N
W
t
a
W
F
l
1
Y
W
1
G
a
k
x
t
U
n
Z
k
R
E
N
D
C
k
F
T
S
X
d
E
U
V
l
K
S
2
9
a
S
W
h
2
Y
0
5
B
U
U
V
C
Q
l
F
B
R
G
d
n
R
V
B
B
R
E
N
D
Q
V
F
v
Q
2
d
n
R
U
J
B
T
H
o
y
d
0
J
N
c
l
Z
m
d
E
1
X
Y
0
F
p
a
2
9
Y
T
n
R
n
W
k
g
K
M
k
M
1
a
0
t
z
T
z
R
Y
V
T
N
U
K
0
N
X
b
D
N
q
d
n
N
H
Q
U
R
1
N
3
E
3
d
F
d
v
V
T
V
x
O
E
9
P
c
0
d
r
V
W
5
P
c
0
N
i
a
2
d
F
U
G
Z
G
a
G
h
I
O
D
l
o
U
W
9
B
a
1
B
l
Y
w
p
T
c
W
M
5
a
U
t
t
U
j
M
4
R
G
x
j
Z
1
M
z
N
l
p
C
S
2
F
r
U
E
F
C
U
z
Q
x
T
E
l
C
Q
X
Z
4
Z
3
E
r
Q
y
9
L
e
m
5
B
U
n
U
z
a
z
J
C
V
E
F
p
S
z
J
0
e
j
d
K
V
j
Z
z
d
k
9
B
C
i
9
X
T
k
J
X
U
H
h
R
T
z
d
I
e
W
p
6
W
k
0
2
W
G
l
w
R
z
J
S
T
T
B
L
R
D
R
U
T
H
Z
P
Y
z
l
m
V
G
Z
X
O
S
8
5
a
U
R
a
R
D
R
z
T
V
N
R
U
i
9
H
e
T
l
R
U
z
Z
O
a
1
N
l
O
V
A
K
S
m
1
j
d
1
p
P
Z
U
d
P
b
W
k
1
Q
1
R
U
c
S
t
H
W
U
5
6
W
k
F
s
Q
T
d
6
b
m
N
X
V
0
l
M
T
m
h
5
a
W
d
2
Z
k
p
v
W
W
I
v
Q
U
J
Y
K
1
V
h
O
W
p
y
d
y
t
O
V
0
F
r
e
m
Z
I
a
w
p
5
V
m
h
B
V
V
B
o
N
1
J
i
W
U
9
p
S
n
g
4
V
H
d
W
Y
U
M
r
b
U
E
4
W
k
p
z
M
T
Z
H
Q
T
h
D
d
l
k
x
e
D
B
6
O
H
J
j
T
T
V
U
Z
k
F
t
K
2
l
m
M
D
Z
G
N
U
I
5
M
D
Z
n
d
z
h
D
C
k
F
3
R
U
F
B
Y
U
9
C
c
F
R
D
Q
m
9
q
Q
W
R
C
Z
0
5
W
S
F
E
0
R
U
Z
n
U
V
V
W
d
0
1
h
U
W
J
v
V
W
Z
q
T
F
h
w
V
0
F
Z
S
3
Q
r
N
j
Z
B
Z
k
8
v
c
z
B
3
S
H
d
Z
R
F
Z
S
M
G
o
K
Q
k
J
n
d
0
Z
v
Q
V
V
W
d
0
1
h
U
W
J
v
V
W
Z
q
T
F
h
w
V
0
F
Z
S
3
Q
r
N
j
Z
B
Z
k
8
v
c
z
B
3
R
H
d
Z
R
F
Z
S
M
F
R
B
U
U
g
v
Q
k
F
V
d
0
F
3
R
U
I
v
e
k
J
Q
Q
m
d
O
V
g
p
I
U
k
V
F
U
0
R
C
R
2
d
o
R
m
t
j
U
z
E
x
Y
V
M
1
a
1
p
Y
W
X
V
h
b
U
Z
q
T
G
1
S
d
m
R
J
S
U
x
a
S
E
V
0
W
m
5
K
d
m
J
u
U
m
x
i
b
V
N
D
S
k
d
S
e
E
x
X
W
n
l
i
M
j
U
w
C
l
p
X
N
W
t
M
b
V
J
4
T
F
d
S
b
G
R
p
N
X
p
k
b
U
1
1
W
T
J
4
M
W
M
z
U
m
x
j
a
T
V
z
Y
j
J
O
a
G
J
E
Q
U
5
C
Z
2
t
x
a
G
t
p
R
z
l
3
M
E
J
B
U
X
N
G
Q
U
F
P
Q
0
F
R
R
U
E
K
R
3
N
W
Z
n
F
j
d
m
h
M
U
n
N
H
d
1
Z
6
M
G
1
B
R
E
J
R
b
W
d
r
R
U
h
y
V
T
A
v
c
E
Z
v
U
n
N
H
Y
n
V
y
Z
T
N
T
c
F
h
y
d
V
V
n
W
X
I
x
T
H
N
1
M
y
t
2
U
1
g
v
b
n
d
G
c
w
p
X
Q
V
h
V
N
W
R
5
S
E
p
I
M
2
M
r
R
n
R
Y
d
V
h
T
R
i
9
D
c
V
B
w
a
X
R
L
W
V
Z
6
a
V
p
3
S
U
N
E
T
0
1
N
W
n
h
y
a
k
U
1
e
X
Z
Z
S
n
N
4
R
W
t
2
c
F
l
I
V
2
Y
2
T
E
h
B
C
m
F
t
Y
0
k
5
c
n
h
3
Z
j
l
p
Y
l
R
5
N
D
V
E
b
H
M
0
W
V
p
Q
O
X
l
G
b
F
R
w
Y
m
N
w
S
k
d
W
W
E
1
6
M
F
U
2
Y
k
x
C
Z
V
d
4
V
m
w
r
T
C
8
0
a
k
M
3
S
m
N
C
d
2
J
U
N
T
E
K
Q
V
N
R
c
G
w
5
c
F
Z
x
e
X
B
E
c
2
w
x
W
G
9
P
b
z
c
1
a
m
h
B
d
E
J
6
S
2
t
R
Y
X
B
w
a
n
J
K
c
m
5
l
M
U
R
Y
S
0
N
n
b
H
R
O
R
j
N
r
R
U
V
J
Z
D
h
v
T
U
1
w
d
n
E
5
V
A
p
G
N
y
8
5
S
W
p
Z
O
V
R
Z
V
k
1
U
V
n
o
2
T
U
R
2
Y
T
R
C
T
z
B
D
a
k
1
s
Z
E
J
U
S
m
Z
x
T
F
V
a
Z
E
N
N
Z
l
R
M
Y
S
t
z
M
0
5
P
Q
0
J
x
R
3
A
v
c
j
l
U
V
H
R
5
R
n
l
4
C
k
E
2
N
z
F
t
S
V
p
L
S
k
d
Q
M
U
J
T
Y
n
N
Z
c
W
N
t
c
k
E
9
P
Q
o
t
L
S
0
t
L
U
V
O
R
C
B
D
R
V
J
U
S
U
Z
J
Q
0
F
U
R
S
0
t
L
S
0
t
C
g
=
=
  tls.key: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
Q
U
k
l
W
Q
V
R
F
I
E
t
F
W
S
0
t
L
S
0
t
C
k
1
J
S
U
V
2
U
U
l
C
Q
U
R
B
T
k
J
n
a
3
F
o
a
2
l
H
O
X
c
w
Q
k
F
R
R
U
Z
B
Q
V
N
D
Q
k
t
j
d
2
d
n
U
2
p
B
Z
0
V
B
Q
W
9
J
Q
k
F
R
Q
z
g
5
c
0
F
U
S
z
F
Y
N
1
R
G
b
k
E
K
S
X
B
L
R
n
p
i
W
U
d
S
O
W
d
1
W
k
N
y
R
H
V
G
M
U
4
w
L
2
d
s
c
G
Q
0
N
z
d
C
Z
0
E
3
d
T
Z
1
N
1
Z
x
R
k
9
h
d
k
R
q
c
k
J
w
R
k
p
6
c
k
F
t
N
U
l
C
R
D
N
4
W
V
l
S
L
w
p
Q
W
V
V
L
Q
U
p
E
M
2
5
F
c
W
5
Q
W
W
l
w
a
2
Q
v
Q
T
V
Y
S
U
V
0
K
2
1
R
U
2
1
w
R
H
d
B
V
X
V
O
U
3
l
B
U
U
w
4
W
U
t
2
Z
3
Z
5
c
z
V
3
R
W
J
0
N
U
5
n
V
X
d
J
a
X
R
y
C
m
M
r
e
V
Z
l
c
k
x
6
Z
1
A
x
a
l
F
W
a
j
h
V
R
H
V
4
O
G
8
4
M
l
R
P
b
D
R
x
U
n
R
r
V
E
5
D
Z
y
t
F
e
T
d
6
b
l
B
Y
M
D
M
x
d
m
Y
v
W
W
c
y
U
S
t
M
R
E
V
r
R
W
Z
4
c
3
Y
K
V
U
V
1
a
l
p
F
b
n
Z
U
e
V
p
u
T
U
d
U
b
m
h
q
c
G
9
1
U
W
s
w
N
n
Z
o
b
U
R
j
M
l
F
K
U
U
8
4
N
T
N
G
b
G
l
D
e
l
l
j
b
2
9
M
M
3
l
h
R
0
c
v
d
0
F
W
L
2
x
H
d
l
k
2
O
A
p
Q
a
l
Z
n
S
k
0
z
e
D
V
N
b
F
l
R
R
k
Q
0
Z
T
B
X
M
k
R
v
a
W
N
m
R
T
h
G
V
2
d
2
c
G
d
Q
R
1
N
i
T
m
V
o
Z
1
B
B
c
j
J
O
Y
2
R
N
L
0
s
z
R
E
9
V
M
3
d
K
d
m
9
u
O
U
9
o
C
m
V
R
Z
m
R
P
b
0
1
Q
Q
W
d
N
Q
k
F
B
R
U
N
n
Z
0
V
B
R
1
p
X
c
H
p
w
b
E
x
m
R
W
1
M
Z
U
F
H
T
H
A
4
K
0
J
H
Y
n
R
E
S
3
p
v
b
l
l
D
Q
1
N
O
d
E
R
B
V
2
J
p
V
T
E
3
V
j
c
K
c
F
M
5
Z
k
9
i
M
V
d
u
W
k
N
B
R
D
h
E
b
3
V
i
d
3
Z
h
Q
2
V
5
e
E
N
W
d
T
R
1
N
W
x
L
M
3
A
v
a
k
5
S
N
W
R
2
Z
S
t
V
O
W
t
p
V
m
5
N
e
k
Z
4
Y
j
U
w
b
W
N
P
N
z
B
P
N
Q
p
a
N
U
E
r
e
m
Z
3
b
n
c
2
V
3
J
P
Z
k
V
p
S
E
F
2
R
m
h
Q
N
z
I
5
e
U
8
z
O
H
N
Y
Q
z
d
l
V
0
s
z
c
3
o
z
Z
G
I
0
U
2
t
M
Y
1
p
x
V
V
U
1
R
C
t
X
R
0
8
3
L
2
1
J
Z
V
B
v
C
k
M
y
e
W
t
w
T
n
k
5
V
j
B
W
c
E
N
B
O
C
t
l
N
i
9
m
a
3
l
6
d
3
F
n
a
k
Y
v
Y
l
N
S
a
U
l
S
L
3
d
R
T
j
h
C
M
3
d
E
R
m
t
Z
N
k
4
3
U
3
p
L
W
D
d
J
S
G
w
v
e
E
d
y
a
2
4
K
V
T
l
j
a
m
Y
1
a
3
h
5
e
j
R
3
Q
0
d
x
b
V
I
r
Y
1
d
w
U
0
Y
5
V
l
Z
I
c
y
9
F
W
E
9
u
M
2
0
2
Y
U
l
H
M
m
s
z
T
V
R
V
c
U
V
p
d
H
V
t
T
H
F
I
S
0
F
k
N
D
R
j
d
1
l
i
Z
w
p
T
Z
2
9
S
T
F
B
6
Y
3
c
r
W
G
V
T
R
E
d
R
c
W
t
h
b
0
J
O
Z
1
Z
K
Z
1
U
v
S
j
Z
v
a
k
w
r
e
l
p
a
Q
k
V
U
d
1
F
L
Q
m
d
R
R
G
R
m
O
G
8
y
a
E
x
x
Z
T
J
P
Q
l
h
T
Y
m
Z
J
C
k
d
k
T
2
x
i
S
X
Z
a
b
l
d
C
d
l
R
j
b
D
Y
2
R
k
F
2
d
0
x
q
a
D
c
y
W
D
c
w
c
2
J
0
Z
l
J
3
N
n
V
q
N
V
h
y
S
D
d
y
b
V
N
6
Y
1
N
H
e
W
N
1
a
G
p
U
b
2
l
3
K
2
d
R
Y
n
Y
K
b
U
J
X
d
0
9
2
M
U
J
a
a
m
F
x
c
F
l
W
a
z
N
O
M
U
V
y
a
H
F
m
b
1
R
K
d
F
R
W
U
G
o
z
R
U
R
K
O
X
B
Y
V
i
9
4
b
0
h
6
c
m
F
5
S
2
t
6
W
G
Y
3
O
C
9
o
S
k
l
W
R
V
B
J
U
A
p
l
Y
W
F
S
S
n
o
3
b
H
p
y
N
k
R
r
S
F
J
F
R
U
d
J
W
T
R
T
U
W
t
5
U
U
t
C
Z
1
F
E
Y
V
p
h
Q
U
h
D
M
2
U
5
W
T
N
K
d
U
x
j
Y
3
k
v
L
0
E
3
T
2
4
v
T
X
Y
v
Z
1
h
p
V
D
Z
E
C
n
g
3
c
j
V
y
c
3
l
T
e
m
h
n
d
E
Y
x
R
W
F
P
d
1
B
j
d
W
5
h
b
G
R
a
S
k
R
X
T
l
d
t
b
i
9
o
Y
X
F
U
S
m
N
Q
W
n
Z
Z
b
S
9
m
N
F
B
T
b
U
9
q
M
X
R
2
c
W
V
K
M
l
E
3
M
T
g
K
R
k
N
W
T
X
p
I
Y
W
J
1
S
0
J
R
d
V
B
t
V
T
d
D
e
m
V
a
Y
2
Z
D
b
U
t
l
c
U
M
5
O
S
8
0
V
X
R
s
c
0
V
J
a
2
t
0
L
3
g
w
W
G
p
H
N
l
o
3
d
T
F
B
R
W
F
D
N
3
V
X
e
k
h
W
Q
w
p
R
O
D
d
F
O
D
d
V
T
k
Z
3
S
0
J
n
U
U
R
Q
Z
X
Q
y
a
T
l
l
K
0
5
6
a
D
l
Q
Q
k
d
t
W
G
t
j
R
z
B
L
a
H
B
T
R
E
4
0
Q
l
J
M
O
G
Z
W
e
S
t
O
b
T
V
4
V
F
h
4
b
U
x
x
d
V
B
X
C
k
l
D
U
n
F
T
b
j
B
O
U
1
R
K
V
1
p
G
U
W
1
Q
O
T
B
s
Y
m
h
q
R
l
h
S
c
k
9
y
Y
l
F
l
a
U
x
x
Q
U
t
y
R
0
N
L
a
2
0
0
e
l
h
W
S
G
h
x
L
3
B
u
c
U
N
u
d
U
t
w
d
3
d
r
Z
D
c
K
b
0
p
3
N
z
B
y
U
0
d
F
U
U
N
F
S
W
J
q
M
j
Z
U
S
3
p
o
a
U
Z
T
V
V
U
4
N
V
Z
u
Y
z
M
w
Y
j
h
h
S
n
N
Y
L
0
p
B
d
E
h
W
K
y
9
n
d
G
V
2
O
T
N
C
O
H
N
L
U
U
t
C
Z
0
F
E
c
g
p
k
S
1
V
T
O
D
B
v
a
z
V
S
S
j
V
0
d
U
V
N
R
3
V
M
a
y
t
D
e
l
F
r
a
W
J
u
T
1
J
B
d
E
F
5
a
V
N
C
K
0
t
H
W
T
Z
1
c
z
h
Y
W
i
s
w
U
0
Z
Z
M
T
Y
4
U
3
M
2
N
z
g
3
T
W
x
x
C
j
J
3
e
m
1
z
W
U
9
a
N
3
R
J
V
3
R
o
Q
2
h
r
V
T
g
4
W
T
F
J
e
E
V
Q
Y
1
d
p
Z
k
c
v
M
C
9
o
a
T
F
B
M
E
w
x
Z
0
V
C
Q
m
1
3
T
0
l
w
S
T
l
N
M
z
R
x
V
G
1
w
M
D
Z
s
Z
0
w
K
a
H
R
u
Q
3
l
F
U
0
h
L
Z
E
p
H
N
D
Q
5
U
z
V
J
e
D
A
4
Q
n
c
v
K
0
d
a
R
0
x
p
Z
z
l
T
T
j
J
q
Z
V
J
1
N
U
F
v
R
0
F
W
V
F
k
v
R
U
k
r
M
G
h
T
b
1
l
m
Q
0
1
l
K
0
N
G
U
w
p
a
U
n
h
B
e
T
N
R
c
V
V
0
S
X
A
r
b
T
J
Z
L
2
h
W
c
m
h
x
T
m
5
j
U
3
l
1
Q
2
1
K
c
F
J
h
S
F
B
W
S
3
B
z
U
W
5
k
M
V
d
k
V
0
Q
4
V
j
B
W
Q
1
N
4
T
l
A
2
Z
H
p
X
R
F
Z
L
C
k
d
B
b
y
9
F
a
2
p
1
O
V
F
m
Z
j
N
x
N
0
4
5
b
U
t
0
d
W
w
w
S
D
Y
z
e
T
B
u
c
F
h
X
d
H
A
x
W
l
F
V
T
X
d
3
Y
0
4
3
Y
3
o
5
L
0
Z
j
V
k
V
i
V
X
p
S
c
m
9
O
Y
2
p
L
c
F
k
K
a
m
p
v
W
V
I
1
Y
U
1
I
Z
n
l
5
Y
1
U
w
Q
U
l
O
Z
X
Y
3
e
U
k
9
C
i
0
t
L
S
0
t
R
U
5
E
I
F
B
S
S
V
Z
B
V
E
U
g
S
0
V
Z
L
S
0
t
L
S
0
K
