apiVersion: v1
kind: Secret
metadata:
  name: dq-engine-tls
  namespace: dq-dev
type: kubernetes.io/tls
data:
  tls.crt: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
D
R
V
J
U
S
U
Z
J
Q
0
F
U
R
S
0
t
L
S
0
t
C
k
1
J
S
U
R
k
R
E
N
D
Q
W
x
5
Z
0
F
3
S
U
J
B
Z
0
l
V
Z
k
J
n
b
G
V
X
W
k
p
O
W
k
R
n
V
T
l
L
V
X
V
K
O
T
l
v
b
l
Q
r
S
j
B
F
d
0
R
R
W
U
p
L
b
1
p
J
a
H
Z
j
T
k
F
R
R
U
w
K
Q
l
F
B
d
0
l
E
R
W
V
N
Q
n
d
H
Q
T
F
V
R
U
F
3
d
1
Z
a
S
E
V
0
W
l
c
1
b
m
F
X
N
W
x
M
b
V
J
s
Z
G
k
1
c
V
l
X
T
X
V
a
R
z
k
w
T
U
I
0
W
E
R
U
S
T
J
N
R
G
d
4
T
k
R
J
e
g
p
N
e
k
1
6
T
V
Z
v
W
E
R
U
S
T
N
N
R
G
d
4
T
k
R
J
e
k
1
6
T
X
p
N
V
m
9
3
S
U
R
F
Z
U
1
C
d
0
d
B
M
V
V
F
Q
X
d
3
V
l
p
I
R
X
R
a
V
z
V
u
Y
V
c
1
b
E
x
t
U
m
x
k
a
T
V
x
C
l
l
X
T
X
V
a
R
z
k
w
T
U
l
J
Q
k
l
q
Q
U
5
C
Z
2
t
x
a
G
t
p
R
z
l
3
M
E
J
B
U
U
V
G
Q
U
F
P
Q
0
F
R
O
E
F
N
S
U
l
C
Q
2
d
L
Q
0
F
R
R
U
E
0
S
m
l
p
e
U
x
p
S
C
t
k
b
X
I
K
Y
V
Z
B
a
2
d
u
N
3
B
G
T
U
k
3
R
G
I
z
W
F
Z
k
a
l
l
r
Q
W
x
u
W
X
R
Q
Z
2
t
N
b
m
h
F
b
D
d
y
R
1
h
h
S
E
1
0
N
W
5
m
S
3
V
1
W
n
Z
s
V
0
8
4
a
W
Z
X
a
H
R
i
T
i
s
1
R
A
p
4
e
F
c
5
c
i
9
0
W
T
l
i
Z
T
V
Z
a
3
Z
t
R
m
t
Y
N
i
s
1
U
j
B
T
W
l
V
v
Z
C
8
z
R
0
M
0
N
0
5
j
S
X
B
n
V
3
U
v
V
0
h
V
a
2
s
1
S
E
N
3
T
0
M
y
U
X
J
y
S
D
h
N
W
X
F
j
C
m
4
x
Q
m
c
1
e
l
d
q
d
j
J
G
a
2
h
G
e
k
5
M
R
F
l
n
d
3
d
m
V
X
J
B
R
2
R
S
e
j
h
z
V
G
p
G
M
m
9
a
c
X
J
m
c
W
F
G
b
T
R
r
S
X
p
D
e
V
J
Z
S
k
9
K
d
U
F
r
c
H
N
F
a
y
8
K
K
3
p
0
U
C
8
4
Z
1
h
M
Y
z
d
p
R
k
t
4
W
U
V
M
Z
3
A
z
U
m
N
C
R
G
M
2
R
C
9
v
V
T
V
Q
O
H
J
r
Z
0
N
3
Y
z
F
E
Z
k
R
q
R
n
V
O
T
T
N
R
Z
T
J
O
W
D
J
o
M
U
1
6
d
1
J
v
Q
g
o
4
O
H
h
j
T
X
V
H
N
l
B
Z
a
T
R
O
N
3
o
w
d
2
J
4
N
j
l
L
d
0
h
w
S
0
M
y
R
m
J
S
M
T
E
y
U
E
1
F
V
E
I
v
Y
i
9
F
R
m
x
L
Q
m
d
U
Q
W
l
k
T
n
V
r
N
2
F
i
V
G
N
H
b
k
w
1
C
k
o
1
N
H
p
E
R
H
U
v
a
3
d
J
R
E
F
R
Q
U
J
v
N
E
d
s
T
U
l
H
a
U
1
C
M
E
d
B
M
V
V
k
R
G
d
R
V
0
J
C
V
H
F
F
S
z
l
Z
e
H
N
3
T
E
F
E
c
W
d
E
d
U
N
U
Q
0
F
Y
b
F
V
H
Q
3
k
K
Z
l
R
B
Z
k
J
n
T
l
Z
I
U
0
1
F
R
0
R
B
V
2
d
C
V
H
F
F
S
z
l
Z
e
H
N
3
T
E
F
E
c
W
d
E
d
U
N
U
Q
0
F
Y
b
F
V
H
Q
3
l
m
V
E
F
Q
Q
m
d
O
V
k
h
S
T
U
J
B
Z
j
h
F
Q
l
R
B
R
A
p
B
U
U
g
v
T
U
U
4
R
0
E
x
V
W
R
F
U
V
J
J
T
U
V
h
Q
0
Z
X
U
n
h
M
V
1
Z
1
W
j
J
s
d
V
p
T
N
W
t
a
W
F
l
1
Y
W
1
G
a
k
x
t
U
n
Z
k
S
U
l
K
W
k
h
F
d
F
p
X
N
W
5
h
V
z
V
s
C
m
d
p
S
m
t
j
U
z
F
s
Y
m
1
k
c
G
J
t
V
X
V
a
S
E
V
0
W
k
d
W
M
k
x
u
T
j
J
Z
e
T
V
q
Y
k
h
W
e
m
R
H
V
n
l
M
b
X
h
2
W
T
J
G
c
0
1
B
M
E
d
D
U
3
F
H
U
0
l
i
M
0
R
R
R
U
I
K
Q
3
d
V
Q
U
E
0
S
U
J
B
U
U
R
h
T
1
p
w
W
E
V
I
a
E
x
o
V
G
0
z
c
E
p
q
V
n
Y
v
O
U
R
u
V
3
h
3
U
U
F
C
N
G
p
y
a
k
x
o
Z
j
B
z
Y
3
R
6
R
1
F
Q
V
k
F
x
R
E
J
S
W
V
l
k
U
g
p
o
M
l
F
N
c
H
o
r
a
W
5
O
c
H
M
x
R
0
k
3
b
j
F
I
O
W
I
x
Y
z
R
h
d
W
R
K
V
F
p
k
W
k
5
O
O
W
E
1
M
X
N
a
M
k
d
T
N
1
Z
y
T
W
J
O
W
D
Z
V
a
W
0
4
K
2
p
R
S
W
9
1
W
W
N
v
C
l
Z
G
a
F
Z
I
R
m
1
X
O
E
Q
v
c
D
d
H
U
E
N
o
e
W
Z
k
b
U
Y
5
S
E
c
z
d
V
p
t
T
E
F
a
c
D
I
2
W
U
9
Z
T
1
R
P
U
D
Z
m
a
D
F
v
R
W
F
a
U
z
M
2
S
m
V
0
e
F
V
3
N
D
I
2
c
E
8
K
V
X
k
3
Z
2
F
D
Q
W
h
w
S
W
x
I
a
W
R
B
Y
k
I
0
d
k
Y
2
c
k
5
3
S
G
d
l
T
0
t
B
c
1
l
2
W
X
p
N
d
n
h
S
S
m
N
S
Q
U
F
m
U
m
1
K
L
2
V
5
S
V
I
v
Q
0
0
r
T
2
N
K
L
z
J
T
b
g
p
z
a
G
R
v
M
D
J
I
T
k
l
0
a
X
M
y
R
F
Y
5
V
X
R
J
Q
l
Z
N
U
0
d
y
N
H
l
N
Y
W
h
E
W
l
c
4
a
2
Z
q
d
W
1
p
T
k
J
S
e
m
5
R
L
3
h
k
Y
0
R
V
V
F
c
x
a
m
F
I
M
G
9
5
M
0
k
1
C
k
J
P
b
T
Z
V
S
U
w
r
M
1
V
B
V
W
M
4
d
n
g
w
T
0
l
L
Z
G
x
Y
O
U
t
a
S
l
Z
U
d
n
B
6
C
i
0
t
L
S
0
t
R
U
5
E
I
E
N
F
U
l
R
J
R
k
l
D
Q
V
R
F
L
S
0
t
L
S
0
K
  tls.key: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
Q
U
k
l
W
Q
V
R
F
I
E
t
F
W
S
0
t
L
S
0
t
C
k
1
J
S
U
V
2
Q
U
l
C
Q
U
R
B
T
k
J
n
a
3
F
o
a
2
l
H
O
X
c
w
Q
k
F
R
R
U
Z
B
Q
V
N
D
Q
k
t
Z
d
2
d
n
U
2
l
B
Z
0
V
B
Q
W
9
J
Q
k
F
R
R
G
d
t
S
0
x
J
d
U
l
m
N
T
J
h
d
H
A
K
V
U
N
T
Q
2
Z
1
a
1
V
3
a
n
N
O
d
m
R
k
V
j
J
O
a
V
F
D
V
2
R
p
M
C
t
D
U
X
l
l
R
V
N
Y
d
X
N
a
Z
G
9
j
e
T
N
t
Z
D
h
x
N
j
V
t
K
1
Z
Z
N
3
l
K
O
W
F
H
M
X
M
z
N
2
t
Q
S
A
p
G
Y
j
J
2
K
z
F
q
M
X
Q
3
b
G
l
T
K
1
l
X
U
m
Z
y
N
2
x
I
U
k
p
s
U
2
g
z
L
2
N
Z
T
G
p
z
M
X
d
p
b
U
J
h
N
z
l
Z
Z
F
N
T
V
G
t
j
T
E
E
0
T
F
p
D
d
X
N
m
d
3
h
p
c
H
l
m
C
l
V
H
R
G
5
O
Y
U
8
v
W
V
d
T
R
V
h
N
M
H
N
O
a
U
R
E
Q
j
l
T
c
0
F
a
M
U
h
Q
e
X
h
P
T
V
h
h
a
G
1
x
d
C
t
w
b
1
d
i
a
V
F
q
T
U
x
K
R
m
d
r
N
G
0
0
Q
1
N
t
d
1
N
U
L
z
c
K
T
z
A
v
L
3
l
C
Y
3
R
6
d
U
l
V
c
k
Z
n
U
X
V
D
b
m
R
G
d
0
V
O
e
m
9
Q
K
2
h
U
a
y
9
5
d
V
N
B
T
E
J
6
V
U
4
4
T
0
1
X
N
D
B
6
Z
E
I
3
W
T
F
m
Y
U
h
V
e
l
B
C
R
2
d
I
e
g
p
6
R
n
d
5
N
G
J
v
O
W
l
M
Z
z
N
2
U
F
R
C
d
k
h
y
M
H
J
B
Z
W
t
v
T
F
l
W
d
E
h
Y
W
F
k
4
d
1
J
N
S
D
l
2
O
F
F
X
V
W
9
H
Q
k
1
D
S
j
A
y
N
l
R
0
c
H
R
O
d
2
F
j
d
m
t
u
C
m
5
q
T
U
1
P
N
y
t
U
Q
W
d
N
Q
k
F
B
R
U
N
n
Z
0
V
B
T
W
l
I
U
D
R
C
Y
l
V
m
e
k
F
Y
Z
z
B
2
W
X
d
t
b
2
F
r
O
E
F
o
R
j
F
t
a
k
t
h
M
2
I
5
U
m
F
z
U
l
p
K
K
2
8
w
T
D
A
K
b
3
J
t
Z
U
o
1
S
m
Q
3
a
n
h
Y
a
E
N
2
O
E
k
w
O
F
B
j
U
X
Z
B
a
W
d
m
b
U
x
n
O
V
l
n
S
1
U
1
T
U
l
G
Z
G
8
0
Z
E
5
j
W
V
A
0
a
V
V
z
N
G
t
S
U
m
J
l
c
H
M
1
S
z
h
O
e
A
p
B
O
T
V
0
d
S
t
1
Z
l
E
x
M
G
F
n
W
E
g
w
c
3
F
y
M
m
9
x
d
U
Z
D
b
0
Y
v
Q
m
Y
z
b
k
p
P
W
j
N
v
d
F
J
G
e
H
k
r
e
G
x
K
d
j
B
U
a
V
N
N
M
2
9
1
d
W
J
I
Q
j
F
6
M
U
4
r
C
j
Z
m
R
X
p
K
d
n
V
n
T
2
I
4
V
3
l
a
d
F
l
4
O
X
h
j
c
k
h
m
c
m
J
6
L
0
N
6
N
l
Y
0
V
l
l
p
N
k
s
y
N
3
Q
4
a
E
h
4
c
k
F
I
N
k
5
U
Z
3
k
1
N
n
B
1
e
U
J
0
d
U
9
I
d
n
M
K
R
k
9
P
c
X
p
6
Q
z
h
k
d
T
F
x
V
H
E
w
c
m
p
h
W
C
t
m
T
1
B
j
N
E
1
L
e
m
F
Y
Z
V
J
m
U
1
R
k
a
D
N
x
b
X
R
4
c
X
Z
x
S
X
l
q
d
k
J
M
Q
U
J
U
U
U
h
v
R
D
h
B
d
E
5
K
T
g
p
R
M
S
t
x
N
H
h
I
e
H
Z
V
d
j
g
4
Z
j
B
n
N
m
J
U
c
z
B
3
d
T
l
Q
V
H
h
t
d
z
R
p
c
2
d
5
b
n
d
S
Y
W
t
M
L
1
F
L
Q
m
d
R
R
D
V
s
T
U
t
2
V
m
l
1
L
0
x
0
W
l
Y
w
d
U
d
L
C
n
B
C
e
m
N
v
T
m
N
s
e
j
N
L
b
z
R
X
S
k
F
5
e
G
U
y
S
V
Z
v
b
n
h
M
V
m
1
O
N
W
1
6
c
G
x
V
Y
1
Z
j
a
1
B
1
c
X
Z
W
Z
2
R
I
Y
2
o
w
d
E
x
O
M
W
h
W
R
k
M
r
a
T
l
J
T
j
Q
K
Q
2
h
w
e
m
R
W
R
W
p
B
a
H
o
y
S
U
Z
Q
R
2
p
H
M
S
9
z
N
z
J
v
e
l
Z
2
U
n
V
Y
T
V
E
x
Z
V
R
w
b
0
F
v
L
0
h
k
V
2
R
C
W
D
d
l
R
G
t
J
O
G
9
D
b
G
x
x
e
H
R
s
W
V
R
Q
c
g
p
C
L
3
M
z
T
H
M
z
c
n
B
P
W
E
h
t
b
m
R
Q
a
H
V
p
Z
j
J
G
Y
T
h
k
U
U
t
C
Z
1
F
E
b
V
g
y
Q
V
R
w
e
k
N
y
O
E
o
v
d
0
5
o
a
n
l
w
R
1
d
m
U
X
d
k
V
0
N
X
b
2
w
3
R
k
x
r
C
j
J
i
Q
U
V
w
c
z
I
5
M
V
R
N
U
3
o
3
Z
T
N
m
d
m
Y
1
O
V
F
H
d
j
N
X
O
V
g
v
c
E
0
w
V
3
V
S
M
U
F
D
U
E
9
N
a
S
9
a
T
V
B
H
b
n
J
5
V
j
I
z
M
z
M
0
W
k
J
D
N
T
d
a
N
F
k
K
c
T
l
E
a
F
R
a
c
U
9
5
N
n
J
s
Z
V
d
S
a
n
B
G
U
U
c
w
N
1
U
4
M
W
d
Y
U
i
9
X
T
k
s
r
O
F
R
R
W
m
M
z
c
0
p
w
U
E
V
5
M
E
R
N
R
F
R
m
N
X
l
R
K
y
9
i
L
0
N
W
Z
0
1
F
U
Q
p
F
V
D
Z
U
V
j
B
x
c
T
V
3
S
0
J
n
R
X
B
T
W
G
x
k
U
V
Z
k
N
n
M
x
K
z
d
l
e
V
l
N
N
3
M
4
e
V
B
x
U
U
g
5
Y
0
t
1
U
j
B
t
e
H
h
E
a
k
t
T
W
k
F
L
T
H
R
X
a
2
5
E
W
U
p
O
C
i
t
m
S
m
l
L
V
2
1
o
c
1
N
I
M
2
N
z
T
T
N
l
T
G
l
C
V
n
J
D
Z
l
B
r
Q
k
1
p
Q
W
5
y
R
0
U
x
a
G
x
q
U
F
N
v
V
V
U
2
Q
X
p
p
U
k
F
O
c
V
N
i
O
X
d
n
c
T
B
N
Y
z
h
v
T
U
U
K
N
3
h
J
V
E
1
u
b
n
h
M
S
G
V
C
O
T
N
H
d
z
F
W
Q
3
d
j
U
0
5
4
Z
k
1
z
S
D
B
5
b
2
V
T
b
F
Q
0
Z
n
l
H
N
U
R
T
U
V
B
m
N
U
F
U
S
U
p
y
W
k
Z
a
c
3
h
B
b
0
d
B
R
j
J
B
e
Q
p
K
W
X
h
m
Z
W
Z
M
d
X
A
3
Y
z
F
q
T
m
w
x
b
m
x
W
M
D
F
4
d
1
p
j
M
E
9
w
b
m
F
N
a
E
l
6
Z
X
h
4
T
U
5
2
Y
l
V
j
N
m
d
4
b
1
Z
H
M
z
N
x
N
y
t
k
d
U
5
1
V
1
V
G
a
2
5
x
C
n
l
K
e
D
l
C
W
j
A
r
R
W
J
I
U
H
M
0
N
G
9
K
U
W
5
F
a
E
l
I
U
z
J
L
c
n
Q
w
Z
D
h
O
V
U
8
5
S
T
h
a
a
G
s
v
T
2
Y
y
Y
2
M
z
b
z
R
O
Q
j
J
v
W
G
V
1
R
z
R
L
M
G
9
w
V
X
Q
K
Z
1
Y
v
e
k
p
6
V
T
Y
1
V
X
N
p
a
G
h
J
S
l
R
n
V
k
M
z
Z
E
F
E
L
z
R
l
V
E
Q
0
a
F
F
h
e
T
c
r
V
3
A
w
Q
2
d
Z
Q
j
M
y
Y
m
s
5
R
2
d
2
S
H
B
Q
U
F
J
Y
K
0
9
I
W
D
d
M
N
Q
o
1
M
T
B
P
O
H
h
s
W
X
N
v
V
1
V
O
M
T
R
J
Q
j
Z
M
S
l
A
v
a
S
9
X
U
1
p
V
S
0
h
K
b
2
l
T
N
n
B
m
V
E
I
4
R
y
8
w
O
X
Z
o
b
W
c
0
U
E
Z
K
K
1
h
E
W
m
N
J
O
V
V
Z
O
X
o
v
C
j
B
q
U
z
F
U
W
m
1
L
O
F
Z
I
a
W
g
1
Z
j
Z
h
Q
3
J
5
d
V
g
0
R
m
x
h
N
m
F
V
V
W
h
t
Y
m
Z
M
Q
U
x
j
Q
X
k
r
S
D
l
I
c
m
Y
4
a
U
V
u
S
S
t
U
R
V
l
J
N
z
h
x
a
n
l
x
R
j
A
K
V
0
M
v
c
D
d
i
N
H
l
r
Y
3
Q
w
b
k
p
T
a
F
Z
W
U
C
9
S
U
T
0
9
C
i
0
t
L
S
0
t
R
U
5
E
I
F
B
S
S
V
Z
B
V
E
U
g
S
0
V
Z
L
S
0
t
L
S
0
K
