apiVersion: v1
kind: Secret
metadata:
  name: dq-ui-tls
  namespace: dq-dev
type: kubernetes.io/tls
data:
  tls.crt: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
D
R
V
J
U
S
U
Z
J
Q
0
F
U
R
S
0
t
L
S
0
t
C
k
1
J
S
U
R
Z
R
E
N
D
Q
W
t
p
Z
0
F
3
S
U
J
B
Z
0
l
V
Y
n
h
j
M
z
l
3
e
j
N
H
c
2
h
y
a
0
U
w
b
z
J
X
S
V
Z
V
S
k
d
J
c
G
9
F
d
0
R
R
W
U
p
L
b
1
p
J
a
H
Z
j
T
k
F
R
R
U
w
K
Q
l
F
B
d
0
h
E
R
W
F
N
Q
m
d
H
Q
T
F
V
R
U
F
3
d
1
J
a
S
E
V
0
Z
F
d
r
d
V
p
H
V
j
J
M
b
X
B
o
W
X
k
1
a
2
I
z
U
X
d
I
a
G
N
O
T
W
p
Z
d
0
9
E
R
T
B
N
a
k
1
6
T
X
p
N
e
A
p
X
a
G
N
O
T
W
p
j
d
0
9
E
R
T
B
N
a
k
1
6
T
X
p
N
e
F
d
q
Q
W
N
N
U
m
9
3
R
0
F
Z
R
F
Z
R
U
U
R
E
Q
k
Z
r
Y
1
M
x
M
W
F
T
N
W
t
a
W
F
l
1
Y
W
1
G
a
k
x
t
U
n
Z
k
R
E
N
D
C
k
F
T
S
X
d
E
U
V
l
K
S
2
9
a
S
W
h
2
Y
0
5
B
U
U
V
C
Q
l
F
B
R
G
d
n
R
V
B
B
R
E
N
D
Q
V
F
v
Q
2
d
n
R
U
J
B
U
E
9
V
Q
T
B
C
b
F
N
O
M
X
V
6
O
X
g
1
L
3
Z
5
b
3
c
y
S
C
8
K
a
n
A
4
Y
0
1
l
W
T
h
m
d
m
h
D
Q
l
l
Y
R
E
g
2
e
U
c
r
Q
k
1
V
R
z
l
r
R
F
I
r
S
j
J
y
Z
k
V
6
M
1
Q
0
V
m
1
I
a
U
F
2
M
W
J
o
V
C
s
0
S
z
l
y
e
m
9
r
V
m
h
L
O
G
I
z
e
Q
p
X
S
1
d
I
c
U
9
0
d
j
V
K
c
D
g
4
M
G
9
E
e
V
l
3
a
k
R
M
N
0
l
w
d
k
J
k
d
3
J
K
Z
E
5
t
W
V
A
z
U
T
h
z
T
H
l
S
S
m
N
N
Y
U
R
E
Z
T
R
x
Z
0
8
v
R
V
l
B
b
U
s
5
Q
3
o
z
C
l
N
Y
Z
n
N
Z
Z
3
N
4
b
j
Q
y
a
H
Q
v
K
0
k
0
Y
k
J
J
V
U
F
m
Y
l
Z
4
R
W
x
O
b
F
I
2
c
2
1
o
R
m
I
3
Y
0
F
a
L
1
k
2
V
n
l
a
Q
3
U
r
Y
V
Z
0
c
S
8
x
S
X
l
r
Q
1
l
r
T
W
E
K
Z
X
d
u
e
m
N
Y
b
m
t
5
M
z
B
n
T
z
B
h
U
z
k
0
R
0
Z
3
b
E
5
W
e
l
h
s
T
k
V
z
a
D
V
W
c
C
9
Z
T
U
1
O
M
W
J
j
V
1
o
y
S
3
J
2
N
n
d
S
N
n
p
Q
U
m
V
l
N
j
V
E
d
T
J
k
a
A
p
k
a
X
J
x
Q
k
t
5
O
G
R
T
U
X
Z
r
d
z
V
K
Z
W
p
6
c
E
Z
2
T
z
A
1
c
2
M
x
d
E
d
s
a
T
N
1
Z
E
9
W
Q
X
l
I
Q
W
5
k
M
E
d
M
b
U
5
D
c
U
l
k
Y
X
B
T
M
k
J
y
R
W
F
v
S
m
N
D
C
k
F
3
R
U
F
B
Y
U
9
C
b
V
R
D
Q
m
x
q
Q
W
R
C
Z
0
5
W
S
F
E
0
R
U
Z
n
U
V
V
S
T
G
p
C
M
G
V
p
M
G
t
3
c
l
l
5
b
2
h
k
M
y
9
I
e
k
1
a
a
m
o
z
b
E
V
3
S
H
d
Z
R
F
Z
S
M
G
o
K
Q
k
J
n
d
0
Z
v
Q
V
V
S
T
G
p
C
M
G
V
p
M
G
t
3
c
l
l
5
b
2
h
k
M
y
9
I
e
k
1
a
a
m
o
z
b
E
V
3
R
H
d
Z
R
F
Z
S
M
F
R
B
U
U
g
v
Q
k
F
V
d
0
F
3
R
U
I
v
e
k
J
E
Q
m
d
O
V
g
p
I
U
k
V
F
U
E
R
B
N
m
d
o
R
m
t
j
U
z
E
x
Y
V
M
1
a
1
p
Y
W
X
V
h
b
U
Z
q
T
G
1
S
d
m
R
J
S
U
Z
a
S
E
V
0
Z
F
d
t
Q
0
h
t
U
n
h
M
W
F
Z
w
T
G
1
S
e
E
x
X
U
m
x
k
a
T
V
6
C
m
R
t
T
X
V
Z
M
n
g
x
Y
z
N
S
b
G
N
p
N
X
N
i
M
k
5
o
Y
k
R
B
T
k
J
n
a
3
F
o
a
2
l
H
O
X
c
w
Q
k
F
R
c
0
Z
B
Q
U
9
D
Q
V
F
F
Q
W
V
B
T
m
h
w
O
W
V
u
M
W
w
w
b
2
d
K
R
2
Y
K
T
1
l
p
T
T
k
z
c
W
1
n
a
E
1
Q
V
F
M
r
e
U
d
C
M
m
h
6
c
W
5
5
e
E
V
E
c
G
F
6
Y
W
1
B
Q
2
9
F
Q
V
J
C
S
U
t
u
b
l
B
6
c
m
9
z
N
m
F
Z
N
V
A
y
Y
W
h
Z
N
2
F
G
b
2
l
l
Z
g
p
w
Z
U
N
4
O
C
9
v
U
E
F
D
d
D
l
x
d
D
V
0
S
U
N
m
O
U
c
4
S
j
B
E
S
H
R
o
c
z
Z
E
a
l
h
6
N
V
B
r
U
T
B
W
b
U
I
w
e
X
Z
o
d
F
Z
j
Y
j
h
t
Q
0
s
0
M
F
h
r
S
l
l
2
a
H
l
m
C
j
V
j
M
2
Z
r
W
W
h
a
U
m
N
B
Z
F
R
1
M
k
9
j
W
m
F
W
W
F
I
1
T
j
d
m
b
T
g
w
U
0
Z
u
M
H
d
V
M
X
E
3
S
2
g
0
a
j
J
p
S
H
l
Z
c
D
V
q
Z
E
9
K
d
k
d
a
a
C
s
r
d
m
5
v
N
z
g
K
N
X
Z
q
R
l
Z
W
S
T
Q
w
U
V
Y
v
T
V
p
a
Q
k
I
4
R
2
R
C
d
G
Z
q
T
0
h
y
W
V
B
J
c
V
N
K
W
n
p
a
d
U
l
T
R
z
R
M
Z
W
4
1
R
0
d
X
Z
G
E
w
Y
V
V
l
M
n
l
l
Y
j
R
Z
a
D
h
Z
K
w
p
m
W
X
B
x
d
U
1
R
T
H
B
U
L
z
l
D
T
m
w
2
c
X
R
H
b
W
x
H
S
j
B
o
T
G
1
O
R
m
N
1
d
1
R
k
Y
1
Z
E
N
W
4
3
a
G
k
z
Q
3
J
n
Z
m
p
2
c
0
t
6
b
E
F
V
d
n
F
K
S
W
Z
p
T
W
p
q
C
j
N
G
c
1
Z
w
Q
T
0
9
C
i
0
t
L
S
0
t
R
U
5
E
I
E
N
F
U
l
R
J
R
k
l
D
Q
V
R
F
L
S
0
t
L
S
0
K
  tls.key: L
S
0
t
L
S
1
C
R
U
d
J
T
i
B
Q
U
k
l
W
Q
V
R
F
I
E
t
F
W
S
0
t
L
S
0
t
C
k
1
J
S
U
V
2
Z
0
l
C
Q
U
R
B
T
k
J
n
a
3
F
o
a
2
l
H
O
X
c
w
Q
k
F
R
R
U
Z
B
Q
V
N
D
Q
k
t
n
d
2
d
n
U
2
t
B
Z
0
V
B
Q
W
9
J
Q
k
F
R
R
H
p
s
Q
U
5
B
W
l
V
q
Z
G
J
z
L
2
M
K
Z
W
Y
3
O
H
F
N
T
m
g
v
N
D
Z
m
S
E
R
I
b
V
B
I
N
z
R
R
Z
1
d
G
d
3
g
r
c
2
h
2
Z
1
R
G
Q
n
Z
a
Q
T
B
m
a
W
R
x
M
3
h
N
O
T
A
r
R
l
p
o
N
G
d
M
O
V
c
0
V
S
9
1
Q
3
Z
h
O
A
o
2
S
k
Z
Z
U
3
Z
H
O
T
h
s
a
W
x
o
N
m
p
y
Y
i
t
T
Y
W
Z
Q
T
k
t
B
O
G
1
N
S
X
d
5
K
3
l
L
Y
n
d
Y
Y
0
t
5
W
F
R
a
b
U
Q
5
M
F
B
M
Q
z
h
r
U
1
h
E
R
2
d
3
M
3
V
L
b
0
R
2
C
n
h
H
Q
U
p
p
d
l
F
z
O
T
B
s
M
z
d
H
S
U
x
N
W
i
t
O
b
2
J
m
L
2
l
P
R
3
d
T
R
k
F
I
M
j
F
j
U
k
p
U
W
l
V
l
c
k
p
v
U
l
c
r
M
0
F
H
Z
j
J
P
b
G
N
t
U
X
J
2
b
W
x
i
Y
X
Y
K
O
V
N
N
c
E
F
t
S
k
R
H
b
n
N
K
O
D
N
G
N
T
V
N
d
D
l
J
R
H
R
H
a
3
Z
l
Q
m
h
j
S
l
R
W
Y
z
E
1
V
F
J
M
S
W
V
W
Y
W
Y
y
R
E
R
E
Z
F
c
z
R
m
1
k
a
X
E
3
K
3
N
F
Z
X
N
6
M
A
p
Y
b
n
V
1
U
T
d
0
b
l
l
Y
W
X
E
2
Z
1
N
z
d
k
h
V
a
0
w
1
T
U
9
T
W
G
8
4
N
l
J
i
e
n
R
P
Y
k
h
O
Y
l
J
w
W
X
Q
3
b
l
R
s
U
U
1
o
d
0
o
z
Z
E
J
p
N
W
p
R
c
W
l
I
V
3
F
V
C
n
R
n
Y
X
h
H
c
U
N
Y
Q
W
d
N
Q
k
F
B
R
U
N
n
Z
0
V
B
Y
3
F
K
d
3
k
x
Q
S
9
0
R
E
1
R
T
V
k
v
Y
T
B
S
Y
3
Q
2
U
U
9
v
b
0
R
w
W
l
E
2
V
3
F
E
Z
l
d
v
Z
X
J
V
R
H
h
h
T
T
U
K
d
2
1
U
Z
T
N
F
b
m
V
m
W
G
J
r
V
X
h
Y
W
k
p
I
e
H
V
a
e
H
d
V
c
1
B
O
V
0
5
r
N
U
R
w
R
k
d
D
Q
W
Y
4
M
2
V
Y
R
k
N
o
a
G
p
z
Q
j
I
0
Q
U
5
U
T
G
t
I
e
X
Z
j
S
V
k
5
b
g
p
V
c
X
p
G
W
U
c
r
S
U
Q
0
Q
3
Q
5
d
W
U
x
W
G
9
3
c
F
h
a
Y
1
F
z
K
1
I
r
M
0
Y
x
M
W
x
D
S
W
t
I
c
W
1
l
V
k
V
G
S
G
V
1
Q
3
R
u
Z
D
R
M
W
E
5
G
R
T
h
z
Y
j
l
q
S
V
A
0
C
n
g
3
a
m
x
n
Z
j
F
6
R
T
h
5
a
U
1
q
Z
G
J
j
c
m
J
2
O
T
Z
M
U
k
w
r
T
2
R
n
d
F
l
V
a
T
d
u
U
j
V
t
O
F
p
R
d
T
M
0
c
D
R
Q
N
C
s
w
Q
i
s
5
U
W
h
T
W
E
9
r
W
j
N
h
U
X
c
K
M
E
E
0
M
D
Z
F
S
H
p
K
K
y
8
1
Z
l
Z
V
a
D
R
F
U
0
J
R
M
3
p
0
d
m
Z
L
M
m
4
w
a
k
p
l
S
n
c
r
b
3
N
j
U
G
8
v
d
j
F
k
T
G
N
o
N
0
s
1
Y
k
t
N
b
E
x
j
Q
m
k
z
S
m
t
0
Z
Q
p
B
M
W
t
6
S
V
N
l
U
y
9
F
S
n
l
Y
W
l
h
o
W
k
d
t
d
E
o
0
U
0
x
O
W
T
N
r
M
X
R
w
b
X
R
R
S
G
5
L
L
2
9
C
V
l
F
L
Q
m
d
R
R
C
9
V
T
W
h
O
Z
V
h
1
b
l
Z
q
e
F
p
T
U
3
B
p
C
m
Y
z
M
m
N
h
L
1
B
6
b
U
V
N
V
V
R
y
V
1
p
S
c
E
h
h
Z
F
d
n
a
2
l
h
U
U
l
K
U
G
l
n
U
m
x
M
a
F
h
T
N
1
l
B
M
j
A
v
a
z
V
i
U
D
N
4
U
k
k
w
Z
3
h
K
T
j
V
3
e
k
Q
r
V
F
c
K
M
0
1
V
e
G
h
F
M
n
l
l
W
G
g
r
O
W
N
Y
Q
T
M
5
Z
2
d
E
K
2
E
0
V
V
R
3
L
3
M
1
N
W
5
o
d
U
1
L
U
F
F
U
Z
F
U
4
Y
W
p
C
U
G
9
a
c
V
c
w
L
2
R
x
Q
j
h
3
Y
m
F
D
V
H
Q
r
L
w
p
M
b
G
F
W
W
j
J
D
N
2
t
M
S
n
I
1
R
C
9
k
d
E
1
k
K
3
Z
S
S
V
M
3
U
U
t
C
Z
1
F
E
M
E
9
5
e
l
h
G
R
3
h
6
R
X
Z
x
d
z
V
S
Z
T
F
v
N
S
t
C
M
2
5
p
N
n
l
p
M
2
Z
0
S
0
Z
D
C
m
5
p
M
D
k
2
d
l
d
L
Q
T
J
2
N
E
t
z
Z
0
t
6
Q
l
V
B
b
2
x
F
R
V
J
H
c
m
p
X
b
E
9
K
O
W
F
4
S
S
9
E
U
l
V
j
Q
X
g
v
e
H
N
x
b
W
l
6
b
E
p
6
Z
2
p
E
b
G
l
V
O
E
9
Z
b
z
U
K
d
l
R
o
S
V
B
3
M
m
R
n
Y
3
A
3
Y
i
9
E
Y
1
l
m
Z
S
9
P
c
j
V
r
d
W
R
k
N
E
l
U
M
0
d
O
O
V
R
h
V
D
V
3
d
k
h
x
M
0
R
h
M
W
N
o
V
V
V
q
Q
3
p
1
S
E
Z
E
S
2
g
4
S
2
9
X
K
w
p
s
S
E
J
D
R
D
J
2
O
U
V
3
S
0
J
n
Q
0
Q
1
U
G
V
W
R
G
0
w
U
3
h
U
b
m
4
1
a
V
E
v
U
G
g
x
b
D
h
W
N
1
Z
P
S
k
5
1
c
W
p
x
b
U
5
B
N
m
x
E
S
U
l
B
W
G
h
x
Z
k
d
u
c
F
d
V
C
m
Y
z
K
z
d
t
U
0
V
z
M
E
I
4
M
T
R
I
U
l
l
T
e
l
p
j
Y
W
x
u
S
1
p
O
S
H
p
h
N
H
F
V
V
0
t
O
Y
2
d
1
e
F
o
0
O
F
l
C
M
T
l
o
a
E
V
I
a
V
R
s
U
2
l
Z
M
V
Q
4
a
z
Q
0
Q
m
I
K
V
z
F
j
b
k
t
r
b
X
J
X
Q
3
d
W
c
U
h
k
S
C
t
t
U
U
g
z
a
E
k
r
c
2
1
P
Q
j
d
F
T
z
B
x
R
m
9
E
V
C
t
y
c
G
R
T
R
2
F
D
T
1
d
K
U
T
N
x
S
z
B
K
c
k
J
B
b
0
d
C
Q
U
1
T
S
Q
p
3
Z
0
t
x
R
3
N
O
W
G
F
J
a
m
x
N
Z
m
t
u
S
E
h
x
a
m
p
q
K
3
g
1
c
3
g
0
V
E
x
T
U
k
d
S
T
V
V
l
b
F
o
v
Z
m
1
r
T
D
l
F
S
k
1
E
R
E
t
n
Y
T
l
X
b
F
F
P
Y
U
h
q
M
l
l
i
C
l
h
u
S
z
F
F
V
j
l
K
Y
z
Z
W
M
1
V
T
a
E
l
M
T
2
V
w
Z
H
Y
v
O
V
d
T
V
m
5
v
R
V
h
x
Y
0
5
v
a
W
M
x
Q
m
1
X
N
H
l
O
Z
m
l
P
N
m
F
t
V
m
1
Y
a
1
F
z
R
U
t
w
S
k
J
h
N
z
I
K
e
X
N
D
T
E
E
4
S
W
Z
T
L
0
Z
Q
O
W
F
P
S
U
I
2
Z
E
1
W
L
z
M
3
d
T
d
G
L
2
Z
u
V
G
9
l
c
F
d
P
V
j
N
Z
b
E
F
v
R
0
J
B
T
G
h
Q
N
l
V
q
U
E
l
n
c
3
B
h
V
H
Z
m
a
U
1
a
d
Q
o
z
K
y
t
Q
R
k
R
O
K
3
F
F
S
m
d
m
e
k
V
E
R
X
I
3
S
k
h
O
T
j
J
3
R
E
l
x
a
z
Z
1
M
2
V
j
d
V
Z
k
Y
1
J
h
V
T
l
S
e
k
p
z
Q
X
Z
r
V
W
N
S
d
k
J
o
Y
3
d
H
a
0
8
z
T
W
l
a
C
k
c
1
S
F
l
o
U
G
J
m
c
U
x
k
e
n
R
E
T
E
1
4
b
G
9
2
S
n
p
i
M
W
R
0
S
n
R
N
a
F
E
z
d
W
1
W
M
X
d
o
a
F
B
m
Z
H
J
D
N
U
Q
x
M
D
F
W
e
U
p
n
U
H
l
s
Q
y
9
S
c
3
c
3
T
m
s
K
O
D
h
2
N
3
Y
v
W
m
5
h
Q
n
N
K
M
G
R
H
b
E
x
K
M
0
c
x
e
G
Z
X
C
i
0
t
L
S
0
t
R
U
5
E
I
F
B
S
S
V
Z
B
V
E
U
g
S
0
V
Z
L
S
0
t
L
S
0
K
