apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dq-made-easy-dev

resources:
  - ../../base/engine
  - config/service-config.yaml
  - config/service-secrets-placeholder.yaml

replicas:
  - name: dq-engine
    count: 1
  - name: dq-profiling
    count: 1
  - name: dq-llm
    count: 1
  - name: dq-openmetadata-db
    count: 1
  - name: dq-openmetadata-server
    count: 1
  - name: dq-kafka-consumer
    count: 1

images:
  - name: docker.io/jacbeekers/dq-made-easy-engine
    newTag: "0.1.0"
  - name: docker.io/jacbeekers/dq-made-easy-profiling
    newTag: "0.1.0"
  - name: docker.io/jacbeekers/dq-made-easy-llm
    newTag: "0.1.0"
  - name: docker.io/jacbeekers/dq-made-easy-kafka-consumer
    newTag: "0.1.0"
  - name: docker.io/jacbeekers/dq-made-easy-openmetadata-db
    newTag: "0.1.0"
  - name: docker.io/jacbeekers/dq-made-easy-openmetadata
    newTag: "0.1.0"
