apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - engine.yaml
  - profiling-worker.yaml
  - trino.yaml
  - llm.yaml
  - openmetadata-db.yaml
  - openmetadata-server.yaml
  - kafka-consumer.yaml

transformers:
  - metadata/labels.yaml
  - metadata/annotations.yaml
