apiVersion: apps/v1
kind: Deployment
metadata:
  name: dq-openmetadata-server
  labels:
    app.kubernetes.io/name: dq-openmetadata-server
    app.kubernetes.io/part-of: dq-made-easy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dq-openmetadata-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dq-openmetadata-server
        app.kubernetes.io/part-of: dq-made-easy
    spec:
      containers:
        - name: dq-openmetadata-server
          image: docker.io/jacbeekers/dq-made-easy-openmetadata:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8585
              name: https
          envFrom:
            - configMapRef:
                name: dq-common-config
            - configMapRef:
                name: dq-openmetadata-server-config
            - secretRef:
                name: dq-openmetadata-server-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: dq-openmetadata-server
  labels:
    app.kubernetes.io/name: dq-openmetadata-server
    app.kubernetes.io/part-of: dq-made-easy
spec:
  selector:
    app.kubernetes.io/name: dq-openmetadata-server
  ports:
    - name: https
      port: 8585
      targetPort: https
