apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config/common-config.yaml
  - ingress/frontend.yaml
  - ingress/keycloak.yaml
  - ingress/openmetadata.yaml
  - jobs/api-migrate.yaml
  - jobs/kong-migrate.yaml
  - jobs/openmetadata-seed.yaml
