apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-api-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  DQ_API_PORT: '8000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-db-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  POSTGRES_DB: dq
