#!/usr/bin/env bash
set -euo pipefail

SOURCE_DIR="/certs/certs"
OUTPUT_DIR="/certs/certs/trust"

mkdir -p "$OUTPUT_DIR"

echo "[trust-bundle] collecting certificates from ${SOURCE_DIR}..."

# Collect all PEM files (certs and CAs, no private keys)
PEM_FILES=()
while IFS= read -r -d '' cert; do
  PEM_FILES+=("$cert")
done < <(find "$SOURCE_DIR" -maxdepth 1 -type f \( -name '*.pem' -o -name '*.crt' \) \
  ! -name '*-key.pem' ! -name '*-key.crt' -print0 | sort -z)

if [ ${#PEM_FILES[@]} -eq 0 ]; then
  echo "[trust-bundle] error: no PEM certificates found in ${SOURCE_DIR}" >&2
  exit 1
fi

echo "[trust-bundle] found ${#PEM_FILES[@]} certificate files"

# --- Generate trust-bundle.pem ---
TRUST_BUNDLE_PEM="${OUTPUT_DIR}/trust-bundle.pem"
> "$TRUST_BUNDLE_PEM"
valid_count=0
for cert in "${PEM_FILES[@]}"; do
  if openssl x509 -in "$cert" -noout 2>/dev/null; then
    cat "$cert" >> "$TRUST_BUNDLE_PEM"
    echo >> "$TRUST_BUNDLE_PEM"
    valid_count=$((valid_count + 1))
  else
    echo "[trust-bundle] warning: skipping invalid cert: $cert" >&2
  fi
done

echo "[trust-bundle] trust-bundle.pem: ${valid_count} certificates"

# --- Generate trust-bundle.jks ---
TRUST_BUNDLE_JKS="${OUTPUT_DIR}/trust-bundle.jks"
# Generate a random truststore password each run
TRUST_PASSWORD="$(openssl rand -hex 12)"
echo "$TRUST_PASSWORD" > "${OUTPUT_DIR}/truststore-password.txt"

# Remove stale keystore from a previous run
rm -f "$TRUST_BUNDLE_JKS"

# Create empty JKS
keytool -genkeypair -keystore "$TRUST_BUNDLE_JKS" \
  -storepass "$TRUST_PASSWORD" -keypass "$TRUST_PASSWORD" \
  -alias __temp__ -dname "CN=temp" -keyalg RSA -keysize 2048 \
  -validity 1 >/dev/null 2>&1
keytool -delete -alias __temp__ -keystore "$TRUST_BUNDLE_JKS" \
  -storepass "$TRUST_PASSWORD" >/dev/null 2>&1 || true

TEMP_PEM="$(mktemp)"
TEMP_ALIAS=0
for cert in "${PEM_FILES[@]}"; do
  if ! openssl x509 -in "$cert" -noout 2>/dev/null; then
    continue
  fi

  TEMP_ALIAS=$((TEMP_ALIAS + 1))
  subject_cn="$(openssl x509 -in "$cert" -noout -subject 2>/dev/null \
    | sed 's/.*CN = //' | tr -dc 'a-zA-Z0-9._-' | head -c 30 || echo "")"
  alias_name="${subject_cn:-cert-${TEMP_ALIAS}}"

  # Handle duplicate aliases
  final_alias="$alias_name"
  dup_count=0
  while keytool -list -keystore "$TRUST_BUNDLE_JKS" \
    -storepass "$TRUST_PASSWORD" -noprompt 2>/dev/null \
    | grep -q "\"${final_alias}\""; do
    dup_count=$((dup_count + 1))
    final_alias="${alias_name}-${dup_count}"
  done

  cp "$cert" "$TEMP_PEM"
  keytool -importcert \
    -keystore "$TRUST_BUNDLE_JKS" \
    -storepass "$TRUST_PASSWORD" \
    -file "$TEMP_PEM" \
    -alias "$final_alias" \
    -noprompt >/dev/null 2>&1 || true
done
rm -f "$TEMP_PEM"
echo "[trust-bundle] trust-bundle.jks: ${valid_count} certificates"

# --- Generate trust-bundle.p12 ---
TRUST_BUNDLE_P12="${OUTPUT_DIR}/trust-bundle.p12"
rm -f "$TRUST_BUNDLE_P12"
openssl pkcs12 -export \
  -out "$TRUST_BUNDLE_P12" \
  -in "$TRUST_BUNDLE_PEM" \
  -name "trust-bundle" \
  -passout "pass:${TRUST_PASSWORD}" \
  -nokeys >/dev/null 2>&1
echo "[trust-bundle] trust-bundle.p12: generated"

# --- Generate java-truststore-env.sh ---
# Source this from any Java entrypoint to set JAVA_OPTS / KC_OPTS.
cat > "${OUTPUT_DIR}/java-truststore-env.sh" << ENVEOF
#!/usr/bin/env bash
# Auto-generated by trust-bundle container.
# Source this to configure Java truststore for all JVM processes.
export JAVA_OPTS="-Djavax.net.ssl.trustStore=${OUTPUT_DIR}/trust-bundle.jks -Djavax.net.ssl.trustStorePassword=${TRUST_PASSWORD} -Djavax.net.ssl.trustStoreType=JKS"
export KC_OPTS="-Djavax.net.ssl.trustStore=${OUTPUT_DIR}/trust-bundle.jks -Djavax.net.ssl.trustStorePassword=${TRUST_PASSWORD} -Djavax.net.ssl.trustStoreType=JKS"
export CURL_CA_BUNDLE="${OUTPUT_DIR}/trust-bundle.pem"
export SSL_CERT_FILE="${OUTPUT_DIR}/trust-bundle.pem"
export REQUESTS_CA_BUNDLE="${OUTPUT_DIR}/trust-bundle.pem"
export DQ_CA_BUNDLE="${OUTPUT_DIR}/trust-bundle.pem"
ENVEOF
chmod +x "${OUTPUT_DIR}/java-truststore-env.sh"
echo "[trust-bundle] java-truststore-env.sh: generated"

# --- Summary ---
echo "[trust-bundle] output directory: ${OUTPUT_DIR}"
ls -la "$OUTPUT_DIR"
echo "[trust-bundle] trust bundle generation complete"
