apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - shared/config/common-config.yaml
  - shared/ingress/frontend.yaml
  - shared/ingress/openmetadata.yaml
  - api/api.yaml
  - api/db.yaml
  - frontend/frontend.yaml
  - engine/engine.yaml
  - profiling/profiling-worker.yaml
  - kafka-consumer/kafka-consumer.yaml
  - openmetadata/openmetadata-db.yaml
  - openmetadata/openmetadata-server.yaml
  - llm/llm.yaml

transformers:
  - engine/metadata/labels.yaml
  - engine/metadata/annotations.yaml
