apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - validation.yaml
  - validation-scripts.yaml
  - dq-role-assignment.yaml
  - kong-bootstrap.yaml

configMapGenerator:
- name: dq-role-assignment-script
  files:
    - dq-role-assignment.sh
- name: dq-kong-bootstrap-script
  files:
    - bootstrap_kong.sh
