apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dq-engine
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dq-engine.example.invalid
      secretName: dq-engine-tls
  rules:
    - host: dq-engine.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dq-engine
                port:
                  number: 8000