apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-common-config
data:
  ENVIRONMENT: dev
  PUBLIC_BASE_URL: https://dq-ui.dev.jac.dot
  TRUST_PROXY_AUTH: "true"
  SSO_PUBLIC_ISSUER_URL: https://keycloak.dev.jac.dot/auth/realms/jaccloud
  KEYCLOAK_PUBLIC_URL: https://keycloak.dev.jac.dot
  OIDC_REDIRECT_BASE_URL: https://dq-ui.dev.jac.dot/api
  REGISTRY_HOST: jacloud.nl/docker