apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dq-api
spec:
  tls:
    - hosts:
        - dq-api.dev.jac.dot
      secretName: dq-api.dev.jac.dot-tls
  rules:
    - host: dq-api.dev.jac.dot