apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dq-ui
spec:
  tls:
    - hosts:
        - dq-made-easy.dev.jac.dot
      secretName: dq-made-easy.dev.jac.dot-tls
  rules:
    - host: dq-made-easy.dev.jac.dot
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dq-frontend
                port:
                  number: 443