connector.name=hive
hive.metastore=file
fs.local.enabled=true
local.location=/tmp/trino-hive-metastore
hive.metastore.catalog.dir=local:///tmp/trino-hive-metastore
fs.s3.enabled=true
s3.endpoint=http://dq-made-easy-aistor:9000
s3.region=us-east-1
s3.aws-access-key=aistoradmin
s3.aws-secret-key=aistoradmin
s3.path-style-access=true
