apiVersion: v1
kind: Secret
metadata:
  name: dq-engine-secrets
type: Opaque
stringData:
  ENGINE_SECRET_PLACEHOLDER: CHANGE_ME_DEV
---
apiVersion: v1
kind: Secret
metadata:
  name: dq-profiling-secrets
type: Opaque
stringData:
  PROFILING_SECRET_PLACEHOLDER: CHANGE_ME_DEV
---
apiVersion: v1
kind: Secret
metadata:
  name: dq-trino-secrets
type: Opaque
stringData:
  TRINO_SECRET_PLACEHOLDER: CHANGE_ME_DEV
---
apiVersion: v1
kind: Secret
metadata:
  name: dq-llm-secrets
type: Opaque
stringData:
  DQ_LLM_API_KEY: CHANGE_ME_DEV
---
apiVersion: v1
kind: Secret
metadata:
  name: dq-kafka-consumer-secrets
type: Opaque
stringData:
  KAFKA_CONSUMER_DB_URL: CHANGE_ME_DEV
---
apiVersion: v1
kind: Secret
metadata:
  name: dq-openmetadata-db-secrets
type: Opaque
stringData:
  OM_DB_PASSWORD: CHANGE_ME_DEV
---
apiVersion: v1
kind: Secret
metadata:
  name: dq-openmetadata-server-secrets
type: Opaque
stringData:
  OM_TOKEN: CHANGE_ME_DEV
