apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-engine-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  DQ_ENGINE_PORT: '8000'
  REDIS_HOST: redis.platform-redis.svc.cluster.local
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_USERNAME: platform-admin
  REDIS_TLS_ENABLED: 'true'
  REDIS_CA_BUNDLE: /etc/ssl/certs/platform-root-ca.pem
  GX_EXECUTION_QUEUE_KEY: dq-made-easy:gx-execution
  GX_JOIN_PAIR_MATERIALIZATION_QUEUE_KEY: dq-made-easy:gx-join-pair-materialization
  TEST_DATA_MATERIALIZATION_QUEUE_KEY: dq-made-easy:test-data-materialization
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-profiling-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  DQ_PROFILING_METRICS_PORT: '8001'
  REDIS_HOST: redis.platform-redis.svc.cluster.local
  REDIS_PORT: '6379'
  REDIS_DB: '0'
  REDIS_USERNAME: platform-admin
  REDIS_TLS_ENABLED: 'true'
  REDIS_CA_BUNDLE: /etc/ssl/certs/platform-root-ca.pem
  PROFILING_QUEUE_KEY: dq-made-easy:profiling
  TEST_DATA_MATERIALIZATION_QUEUE_KEY: dq-made-easy:test-data-materialization
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-trino-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  TRINO_HTTP_PORT: '8080'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-llm-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  DQ_LLM_PORT: '8000'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-kafka-consumer-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  KAFKA_CONSUMER_METRICS_PORT: '9100'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-openmetadata-db-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  POSTGRES_DB: openmetadata_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-openmetadata-server-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  OPENMETADATA_SERVER_PORT: '8585'
