apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-openmetadata-db-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  POSTGRES_DB: openmetadata_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-openmetadata-server-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  OPENMETADATA_SERVER_PORT: '8585'
