apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dq-made-easy-dev

resources:
  - ../../base/api
  - config/service-config.yaml

replicas:
  - name: dq-api
    count: 1
  - name: dq-db
    count: 1

images:
  - name: docker.io/jacbeekers/dq-made-easy-api
    newTag: "0.1.0"
  - name: docker.io/jacbeekers/dq-made-easy-db
    newTag: "0.1.0"
