apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dq-made-easy-dev

resources:
  - ../../base/llm

labels:
  - includeSelectors: true
    pairs:
      platform.jaccloud.nl/managed-by: argocd
      platform.jaccloud.nl/tenant: dq-made-easy
      platform.jaccloud.nl/environment: dev

images:
  - name: docker.io/jacbeekers/dq-made-easy-llm
    newName: docker-registery.host.dev.jac.dot:10443/jacbeekers/dq-made-easy-llm
    newTag: "0.11"
