apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-frontend-config
  labels:
    platform.jaccloud.nl/tenant: dq-made-easy
    platform.jaccloud.nl/environment: dev
data:
  FRONTEND_HTTPS_PORT: '443'
