"""Initial schema

Revision ID: 724b9ef3247c
Revises: 
Create Date: 2026-04-06 01:20:06.166219
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '724b9ef3247c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('config_key', sa.Text(), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ruleid', sa.Text(), nullable=True),
    sa.Column('ruleattributeid', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('requesterid', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.Text(), nullable=True),
    sa.Column('acted_by', sa.Text(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('approvalid', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('actorid', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_objects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_products',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('workspace_id', sa.Text(), server_default='default', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source_metadata',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('connection_string', sa.Text(), nullable=True),
    sa.Column('column_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_count', sa.BigInteger(), nullable=True),
    sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quality_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_profiled_at', sa.DateTime(), nullable=True),
    sa.Column('profiled_by_user_id', sa.Text(), nullable=True),
    sa.Column('profiling_method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id')
    )
    op.create_table('gx_suite_registry',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('suite_id', sa.Text(), nullable=False),
    sa.Column('suite_version', sa.Integer(), nullable=False),
    sa.Column('artifact_version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('data_object_id', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.Text(), nullable=True),
    sa.Column('data_product_id', sa.Text(), nullable=True),
    sa.Column('gx_suite_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compiler_version', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('saved_by', sa.Text(), nullable=True),
    sa.Column('source_pipeline', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'deprecated', 'disabled')", name='ck_gx_suite_registry_status'),
    sa.CheckConstraint('data_object_id IS NOT NULL OR dataset_id IS NOT NULL OR data_product_id IS NOT NULL', name='ck_gx_suite_registry_assignment_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'suite_version', name='uq_gx_suite_registry_suite_version')
    )
    op.create_index('ix_gx_suite_registry_data_object_status', 'gx_suite_registry', ['data_object_id', 'status'], unique=False)
    op.create_index('ix_gx_suite_registry_data_product_status', 'gx_suite_registry', ['data_product_id', 'status'], unique=False)
    op.create_index('ix_gx_suite_registry_dataset_status', 'gx_suite_registry', ['dataset_id', 'status'], unique=False)
    op.create_table('gx_suite_status_history',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('suite_id', sa.Text(), nullable=False),
    sa.Column('suite_version', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gx_suite_status_history_changed_at', 'gx_suite_status_history', ['changed_at'], unique=False)
    op.create_index('ix_gx_suite_status_history_suite', 'gx_suite_status_history', ['suite_id', 'suite_version'], unique=False)
    op.create_table('reusable_filters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filter_expression', sa.Text(), nullable=False),
    sa.Column('workspace', sa.Text(), server_default='default', nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reusable_joins',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('join_definition', sa.Text(), nullable=False),
    sa.Column('workspace', sa.Text(), server_default='default', nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('workspace', sa.Text(), server_default='default', nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_attributes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ruleid', sa.Text(), nullable=True),
    sa.Column('attributeid', sa.Text(), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('threshold_override', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=True),
    sa.Column('dimension', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('generated', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('template_id', sa.Text(), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('createdby', sa.Text(), nullable=True),
    sa.Column('last_approval_by', sa.Text(), nullable=True),
    sa.Column('last_approval_status', sa.Text(), nullable=True),
    sa.Column('last_approval_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_on', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Text(), nullable=True),
    sa.Column('suggestion_id', sa.Text(), nullable=True),
    sa.Column('join_conditions', sa.Text(), nullable=True),
    sa.Column('alias_mappings', sa.Text(), nullable=True),
    sa.Column('reusable_join_id', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('check_type', sa.Text(), nullable=True),
    sa.Column('check_type_params', sa.Text(), nullable=True),
    sa.Column('manual_override_by', sa.Text(), nullable=True),
    sa.Column('manual_override_at', sa.DateTime(), nullable=True),
    sa.Column('total_versions', sa.Integer(), server_default='1', nullable=True),
    sa.Column('versioning_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('version_created_at', sa.DateTime(), nullable=True),
    sa.Column('version_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_info',
    sa.Column('info_key', sa.Text(), nullable=False),
    sa.Column('info_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('info_key')
    )
    op.create_table('test_proofs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ruleid', sa.Text(), nullable=False),
    sa.Column('test_date', sa.DateTime(), nullable=True),
    sa.Column('coverage', sa.Numeric(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('records_tested_count', sa.Integer(), nullable=True),
    sa.Column('failures_found', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Numeric(), nullable=True),
    sa.Column('test_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('tested_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('workspaces', sa.Text(), nullable=True),
    sa.Column('preferences', sa.Text(), server_default='{"display":{"theme":"auto"}}', nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.Text(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('valid_count', sa.Integer(), nullable=True),
    sa.Column('invalid_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='complete', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_test_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ruleid', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('test_data_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('proof_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['proof_id'], ['test_proofs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ruleid'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Text(), server_default='default', nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['data_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_source_profiling_requests',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.Text(), nullable=False),
    sa.Column('requested_by_user_id', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_metadata_id', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_source_metadata.data_source_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gx_suite_execution_target_map',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('suite_id', sa.Text(), nullable=False),
    sa.Column('suite_version', sa.Integer(), nullable=False),
    sa.Column('data_object_version_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id', 'suite_version'], ['gx_suite_registry.suite_id', 'gx_suite_registry.suite_version'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'suite_version', 'data_object_version_id', name='uq_gx_suite_execution_target_map')
    )
    op.create_index('ix_gx_suite_execution_target_map_version', 'gx_suite_execution_target_map', ['data_object_version_id'], unique=False)
    op.create_table('gx_suite_rule_map',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('suite_id', sa.Text(), nullable=False),
    sa.Column('suite_version', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['suite_id', 'suite_version'], ['gx_suite_registry.suite_id', 'gx_suite_registry.suite_version'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id', 'suite_version', 'rule_id', name='uq_gx_suite_rule_map')
    )
    op.create_table('rule_reusable_filters',
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('reusable_filter_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reusable_filter_id'], ['reusable_filters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id', 'reusable_filter_id')
    )
    op.create_table('rule_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('change_type', sa.Text(), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('dimension', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_template', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('template_id', sa.Text(), nullable=True),
    sa.Column('check_type', sa.Text(), nullable=True),
    sa.Column('check_type_params', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('marked_for_rollback', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('validation_status', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'id', name='uq_rule_versions_rule_id_id'),
    sa.UniqueConstraint('rule_id', 'version_number', name='uq_rule_versions_rule_version_number')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('validation_run_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('rule_name', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('warnings', sa.Integer(), nullable=True),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['validation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_objects_catalog',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('dataset_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('latest_version_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['data_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_current_versions',
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id', 'version_id'], ['rule_versions.rule_id', 'rule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('rule_rollbacks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('from_version_id', sa.Text(), nullable=False),
    sa.Column('to_version_id', sa.Text(), nullable=False),
    sa.Column('rolled_back_by', sa.Text(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('new_version_created_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_version_created_id'], ['rule_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_version_compiler_artifacts',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('rule_version_id', sa.Text(), nullable=False),
    sa.Column('compiler_version', sa.Text(), nullable=False),
    sa.Column('compiler_revision', sa.Integer(), nullable=False),
    sa.Column('artifact_key', sa.Text(), nullable=False),
    sa.Column('artifact_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnostics_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compile_status', sa.Text(), nullable=False),
    sa.Column('source_fingerprint', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_version_diffs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('from_version_id', sa.Text(), nullable=False),
    sa.Column('to_version_id', sa.Text(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_version_relationships',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.Text(), nullable=True),
    sa.Column('test_proof_id', sa.Text(), nullable=True),
    sa.Column('deployment_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approvals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_proof_id'], ['test_proofs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('data_source_id', sa.Text(), nullable=False),
    sa.Column('suggested_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.Text(), nullable=True),
    sa.Column('created_from_profiling_request_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_from_profiling_request_id'], ['data_source_profiling_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_deliveries',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('data_object_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('record_count', sa.BigInteger(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('attributes_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_object_id'], ['data_objects_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_object_versions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('data_object_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('schema_hash', sa.Text(), nullable=True),
    sa.Column('attribute_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_object_id'], ['data_objects_catalog.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggestion_interactions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('suggestion_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('rule_created_from_suggestion_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['suggestion_id'], ['suggestions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributes_catalog',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('nullable', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('is_cde', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_primary_key', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('data_object_id', sa.Text(), nullable=True),
    sa.Column('version_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['data_object_id'], ['data_objects_catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['data_object_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attributes_catalog')
    op.drop_table('suggestion_interactions')
    op.drop_table('data_object_versions')
    op.drop_table('data_deliveries')
    op.drop_table('suggestions')
    op.drop_table('rule_version_relationships')
    op.drop_table('rule_version_diffs')
    op.drop_table('rule_version_compiler_artifacts')
    op.drop_table('rule_rollbacks')
    op.drop_table('rule_current_versions')
    op.drop_table('data_objects_catalog')
    op.drop_table('validation_run_items')
    op.drop_table('user_roles')
    op.drop_table('rule_versions')
    op.drop_table('rule_reusable_filters')
    op.drop_table('gx_suite_rule_map')
    op.drop_index('ix_gx_suite_execution_target_map_version', table_name='gx_suite_execution_target_map')
    op.drop_table('gx_suite_execution_target_map')
    op.drop_table('data_source_profiling_requests')
    op.drop_table('data_sets')
    op.drop_table('batch_test_requests')
    op.drop_table('workspaces')
    op.drop_table('validation_runs')
    op.drop_table('users')
    op.drop_table('test_proofs')
    op.drop_table('system_info')
    op.drop_table('sessions')
    op.drop_table('rules')
    op.drop_table('rule_attributes')
    op.drop_table('roles')
    op.drop_table('reusable_joins')
    op.drop_table('reusable_filters')
    op.drop_index('ix_gx_suite_status_history_suite', table_name='gx_suite_status_history')
    op.drop_index('ix_gx_suite_status_history_changed_at', table_name='gx_suite_status_history')
    op.drop_table('gx_suite_status_history')
    op.drop_index('ix_gx_suite_registry_dataset_status', table_name='gx_suite_registry')
    op.drop_index('ix_gx_suite_registry_data_product_status', table_name='gx_suite_registry')
    op.drop_index('ix_gx_suite_registry_data_object_status', table_name='gx_suite_registry')
    op.drop_table('gx_suite_registry')
    op.drop_table('data_source_metadata')
    op.drop_table('data_products')
    op.drop_table('data_objects')
    op.drop_table('audit')
    op.drop_table('approvals')
    op.drop_table('app_config')
    # ### end Alembic commands ###