apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-common-config
data:
  ENVIRONMENT: prod
  PUBLIC_BASE_URL: https://dq-made-easy.eu
  SSO_PUBLIC_ISSUER_URL: https://dq-made-easy.eu/iam/realms/jaccloud
  KEYCLOAK_PUBLIC_URL: https://dq-made-easy.eu/iam
  OPENMETADATA_PUBLIC_URL: https://dq-made-easy.eu/openmetadata
  OIDC_REDIRECT_BASE_URL: https://dq-made-easy.eu/api
  REGISTRY_HOST: docker.io
