apiVersion: v1
kind: ConfigMap
metadata:
  name: dq-keycloak-config
  labels:
    app.kubernetes.io/name: dq-keycloak-config
    app.kubernetes.io/part-of: dq-made-easy
data:
  ENVIRONMENT: dev
  KEYCLOAK_ADMIN_REALM: master
  KEYCLOAK_INTERNAL_URL: https://keycloak.platform-keycloak.svc.cluster.local:8443/auth
  KEYCLOAK_REALM: dq-made-easy