apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dq-db-data
  labels:
    app.kubernetes.io/name: dq-db
    app.kubernetes.io/part-of: dq-made-easy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
