apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dq-api
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dq-api.example.invalid
      secretName: dq-api-tls
  rules:
    - host: dq-api.example.invalid
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dq-api
                port:
                  number: 4010